from dataStructure import Area, Subarea, Formation, Route, Variation
from GB_Book import book


Area(name='Clear Cut Boulders',
     parent=book,
     gps='44.43480966863281, -122.5974049928017',
     description='A small patch of boulders has been recently developed on Quartzville about mile closer to town from the main Garden area. Although the rock quality here is not as solid as other areas, there are a few great lines available in this sector. At present (2025) the area has been clear cut and replanted, until the trees grow this area offers all day sun. The fast drying boulders are a great option for winter weather windows.'
     '\n\n'
     'After parking wherever you can manage on the side of the road search for a faint trail through the buffer of vegetation leading into the Clear Cut.')
Subarea(name='',
        item_id='Clear Cut',
        parent=book.areas['Clear Cut Boulders'],
        format_options=['suppress_page_break'])
        
Formation(name='Star Gazer',
           parent=book.subareas['Clear Cut'],
           description='A small boulder with a large shelf mid way up its face sits at the bottom of the hill.')
Formation(name='Dig Dug',
           parent=book.subareas['Clear Cut'],
           description='This boulder features a well excavated down hill face and a little stone hat.',)
Formation(name='Grizzly Face',
           parent=book.subareas['Clear Cut'],
           description='A long low angle boulder next to the Bear Back.',)
Formation(name='Bear Back',
           parent=book.subareas['Clear Cut'],
           description='Look for this unassuming slab midway up the hill.',)
Formation(name='Double Stump',
           parent=book.subareas['Clear Cut'],
           description='A large boulder with a prominent down hill face can be recognized by the titular double stumps which adorn it (one above it and on below).',)
Formation(name='Cuneiform',
           parent=book.subareas['Clear Cut'],
           description='A wedge shaped boulder sits at the top of the hill.',)
           
Route(name='Huygens',
      parent=book.formations['Star Gazer'],
      grade=2, 
      rating=0, 
      description='Climb the left arete of the boulder through the big ledge. This route used to have a more coherent start, but a key foothold has broken and establishing is now very difficult.')
Route(name='Fleming',
      parent=book.formations['Star Gazer'],
      grade=3,
      rating=1,
      description='Sit start with holds low on the center of the main face of the boulder.')
Route(name='Galileo',
      parent=book.formations['Star Gazer'],
      grade=3,
      rating=1,
      description='Sit start on the excavated right side of the boulder using a low left and undercling and a right hand sidepull. Starting with slightly higher hand holds may result in a more enjoyable experience.')
Route(name='Skrunch',
      parent=book.formations['Dig Dug'],
      grade=3,
      rating=1,
      description='Squat start on the obvious low ledge and skrunch yourself straight up.')
Route(name='Mud Flaps',
      parent=book.formations['Dig Dug'],
      grade=5,
      rating=2,
      description='Awkward sit start on the big sloper lump. Some committing moves through small crimps lead up and left.')
Route(name='Fly Guy',
      parent=book.formations['Dig Dug'],
      grade=2,
      rating=2,
      description='Stand start on a head height pair of edges in the center of the face. A few gymnastic moves bring you to the top.')
Route(name='Tear Duct',
      parent=book.formations['Dig Dug'],
      grade=4,
      rating=2,
      description='Climb the slopey rail from a good flat crimp.')
Route(name='Tear Duct Finish',
      parent=book.formations['Dig Dug'],
      grade=1,
      serious=2,
      description='Climb the little boulder above Dig Dug either as a standalone route or as a second pitch continuing any of the routes below.')
Route(name='Baloo',
      parent=book.formations['Grizzly Face'],
      grade=2,
      description='Sit start on the left side of the downhill face.')
Route(name='Br\'er Bear',
      parent=book.formations['Grizzly Face'],
      grade=2,
      description='Sit start on the right side of the downhill face.')
Route(name='Bald Bear',
      parent=book.formations['Bear Back'],
      grade=2,
      rating=2,
      description='Sit start on a prominent jug ledge.')
Route(name='Wally',
      parent=book.formations['Bear Back'],
      grade=3,
      rating=2,
      serious=1,
      description='Stand start on a left facing flake. Trend left along the slopely lip before mantling onto the slab.')
Route(name='Roman Craig',
      parent=book.formations['Bear Back'],
      grade=1,
      rating=2,
      serious=1,
      description='Stand start as for Wally and climb straight up.')
Route(name='Chet Ripley',
      parent=book.formations['Bear Back'],
      grade=0,
      rating=2,
      serious=1,
      description='Climb straight up the far right side of the boulder')
Route(name='Ballistics Dummy',
      parent=book.formations['Double Stump'],
      grade=4,
      rating=2,
      description='Squat start on a large left facing rail. Climb the left side of the boulder using off balance holds.')
Route(name='Double Stump Project',
      parent=book.formations['Double Stump'],
      grade='?',
      description='A sit start in a small cave on the right side of the boulder leads to an obvious line of crimps up the center of the face.')
Route(name='Chump Mantle',
      parent=book.formations['Double Stump'],
      grade=1,
      rating=3,
      description='Sit start on a blocky right facing rail. Throw to the obvious flake and perform a technical mantle.')
Route(name='Unknown',
      item_id='Cuneiform1',
      parent=book.formations['Cuneiform'],
      grade=0,
      description='The ledgy left face of the boulder looks pretty trivial to climb.')
Route(name='Walk the Line',
      parent=book.formations['Cuneiform'],
      grade=2,
      rating=2,
      serious=1,
      description='Climb the tallest part of the boulder from a stand start. If this route cleans up it will be a classic.')
Route(name='Cuneiform Project',
      parent=book.formations['Cuneiform'],
      grade='?',
      description='An obvious line follows the series of rails along the rise of the boulders wedge shaped face.')
Route(name='Eridu',
      parent=book.formations['Cuneiform'],
      grade=1,
      rating=1,
      description='climb the right hand side of the boulder to and early exit.')
      
Variation(name='Fly Guy SDS',
          parent=book.routes['Fly Guy'],
          grade=4,
          rating=1,
          description='Sit start on Mud Flaps and link into Fly Guy.')
Variation(name='Mud Puppy',
          parent=book.routes['Mud Flaps'],
          grade=4,
          rating=2,
          description='Skip the first few moves of Mud Flaps and start by squatting onto small crimps instead.')
Variation(name='Tear Duct Direct',
          parent=book.routes['Tear Duct'],
          grade=1,
          rating=1,
          description='Start as for Tear Duct but climb straight up.')
Variation(name='Double Stump Project Right',
          parent=book.routes['Double Stump Project'],
          grade='?',
          description='Start as for the Double stump project but climb straight up the blunt arete over a bad landing.')
      

if __name__ == '__main__':
    sys.exit()