from dataStructure.Area import Area
from dataStructure.Subarea import Subarea
from dataStructure.Formation import Formation
from dataStructure.Route import Route
from dataStructure.Variation import Variation
from GB_Book import book


Area(name='Upper Garden',
     parent=book,
     gps='44.43959094940084, -122.58215256842753',
     description='Located about 3.2 miles down Quartzville Road from Highway 20, park in the gravel pull out where the road bends '
                 'about 0.1 miles before you reach a left hand turnoff to a gated logging road (MS-310). Follow the '
                 'logging road approximately 200 yards up hill until it veers slightly to the right. Look for a '
                 'trail that cuts right through a thin patch of trees to the boulder field (Note: there are a '
                 'couple of trails and its worth getting on the most tread one as the others are unpleasant). This '
                 'area is also known as Armageddon or The Clear Cut.'
                 '\n\n'
                 'Many sections of this area are covered in poison oak. Climbers are advised to wear close toed shoes and pants when recreating in this area. If unfamiliar with the plant review the section on poison oak in this book\'s introduction.'
                 '\n\n'
                 'Although the Upper Garden appears overgrown, this entire area was clear cut in the early 2000s. Following the clear cut there was almost no vegetation in the area and it was relatively easy to approach and develop the Upper Garden\'s many boulders. This is why the photos in this guide look dramatically different from photos in guides from that era. Even the most isolated and overgrown boulders in this area already have names and routes on them, many of these boulders have been omitted from this guide since they have been swallowed by the poison oak.',)
                 
               
Subarea(name='Entrance Area',
        item_id = 'entranceUpper',
        gps='44.43961303214984, -122.58215061970166',
        parent=book.areas['Upper Garden'],)
Subarea(name='The Bread Loaves/Scratch and Spliff',
        item_id = 'The Bread Loaves',
        parent=book.areas['Upper Garden'],
        gps='44.43968787057463, -122.58169628966748',
        description='These two boulders are the area\'s main attraction. Historically some groups have called both '
                    'boulders Scratch and Spliff while others called them both the Bread Loaves. The modern compromise '
                    'seems to be that the upper boulder is Scratch and Spliff while the lower boulder is the Bread Loaf.')
Subarea(name='Dr. Strangelove',
        gps='44.44032, -122.58091',
        parent=book.areas['Upper Garden'],
        note = 'This sub area is still being rediscovered. Look forward to more information in future revisions of this book or contribute your own knowledge on github.',
        description='More boulders lay under the canopy beyond the talus NE of the scratch and spliff area. Although there is a lot of poison oak in the way there is one passage which avoids most of it. From the scratch and spliff boulder walk across jumbled talus towards the cliff band for ~100\' until you pass a large fir tree. From here the distinctive prow of the Dr. Stanglove boulder should be barely visible through the trees. Walk more or less directly towards it bushwhacking along a feint trail once you get into the trees. There is much less poison oak under the canopy but it can still be found in some patches. Alternatively you can follow the approach trail through the Middle Garden and avoid all of the poison oak.')
Subarea(name='Machete Monkey',
        gps='44.44034, -122.58015',
        parent=book.areas['Upper Garden'],
        note = 'This sub area is still being rediscovered. Look forward to more information in future revisions of this book or contribute your own knowledge on github.',
        description='About 100\' east of Dr. Strangelove there is a narrow wash of boulders in a clearing. If Approaching from the west follow a faint trail leading from the backside of the Dr. Strangelove boulder to the cliff and walk along the base of the cliff until the trail leads down a steep hill towards the Machete Monkey boulder. If approaching from the East head west from the Jaws boulder ~75\' until you reach the Duck Twirler boulder.')
Subarea(name='Middle Garden',
        gps='44.44034, -122.57973',
        parent=book.areas['Upper Garden'],
        note = 'This sub area is still being rediscovered. Look forward to more information in future revisions of this book or contribute your own knowledge on github.',
        description='There are many boulders under the cliff line east of the Machete Monkey area. Rediscovering and reestablishing this sector is an ongoing project. In 2024 a new trail was established which allows access to this area directly from the road.')
Subarea(name='Upper Forest',
        gps='44.43944, -122.58402',
        parent=book.areas['Upper Garden'],
        description='This is a catch all sub area for everything further up the gravel road from the main Upper Garden trail. Although many boulders in this sector have been climbed historically the Upper Forest has become overgrown and is only recently (2025) being re-established.',
        note = 'This sub area is still being rediscovered. Look forward to more information in future revisions of this book or contribute your own knowledge on github.',)  
                    
Formation(name='The Story of O Boulder',
           gps='44.43944, -122.58402',
           format_options=['suppress_gps'],
           parent=book.subareas['Upper Forest'],
           description='This secluded boulder can be found about 50\' west of the forest road. When heading up hill enter the bushes just before a tall rotten stump approximately 50\' before the fork in the logging road.')
Formation(name='Titanium Boulder',
           gps='44.44035, -122.58365',
           format_options=['suppress_gps'],
           parent=book.subareas['Upper Forest'],
           description='From the fork in the logging road look for a faint trail that leads through a section of low under bush and across a few improvised log bridges through a swampy section. Watch out for poison oak just uphill of this boulder.')
Formation(name='Foxglove Boulder',
           gps='44.44, -122.58466',
           format_options=['suppress_gps'],
           parent=book.subareas['Upper Forest'],
           description='Approximately 70\' up the logging road past the fork head left into the bushes to find this little boulder after roughly 50\' of bush whacking.')
Formation(name='Pumpkin', 
           gps='44.43961, -122.58215',
           format_options=['suppress_gps'],
           parent=book.subareas['entranceUpper'],
           description='This is the first boulder that you encounter when approaching the area.')
Formation(name='Baseball',
           gps='44.43985, -122.58199',
           format_options=['suppress_gps'],
           parent=book.subareas['entranceUpper'],
           description='This is one of the few boulders that isn\'t covered in poison oak, but there is quite a lot of it '
                       'sounding it. Approach with caution.')
Formation(name='Bread Loaf',
           gps='44.43968, -122.58168',
           format_options=['suppress_gps'],
           parent=book.subareas['The Bread Loaves'],
           description='')
Formation(name='Scratch and Spliff',
           gps='44.43967, -122.58163',
           format_options=['suppress_gps'],
           parent=book.subareas['The Bread Loaves'],
           description='')
Formation(name='Dr. Strangelove',
           gps='44.44032, -122.58091',
           format_options=['suppress_gps'],
           parent=book.subareas['Dr. Strangelove'],
           description='')
Formation(name='Kick It',
           gps='44.44027, -122.58119',
           format_options=['suppress_gps'],
           parent=book.subareas['Dr. Strangelove'],
           description='')
Formation(name='Mega Good Boulder',
           gps='44.44022, -122.58124',
           format_options=['suppress_gps'],
           parent=book.subareas['Dr. Strangelove'],
           description='')
Formation(name='Algebra',
           gps='44.44031, -122.58119',
           format_options=['suppress_gps'],
           parent=book.subareas['Dr. Strangelove'],
           description='This small chossy block would be easy to overlook, but the sole line on it is actually much more fun than you might think.')
Formation(name='Crack Boulder',
           gps='44.44035, -122.58041',
           format_options=['suppress_gps'],
           parent=book.subareas['Machete Monkey'],
           description='')
Formation(name='Machete Monkey',
           gps='44.44035, -122.58034',
           format_options=['suppress_gps'],
           parent=book.subareas['Machete Monkey'],
           description='This huge pancake shaped boulder is propped upright and mostly hanging wedged between smaller blocks. So far only the routes on the back side are documented, though there is some evidence in prior guidebooks that the main face may have been climbed before.')
Formation(name='June 24th',
           gps='44.44034, -122.58015',
           format_options=['suppress_gps'],
           parent=book.subareas['Machete Monkey'],
           description='')
Formation(name='Young Ju¢y',
           gps='44.44024, -122.58017',
           format_options=['suppress_gps'],
           parent=book.subareas['Machete Monkey'],
           description='Just down from June 24 there\'s a sloping half moon boulder.')
Formation(name='Duck Twirler',
           gps='44.44022, -122.58003',
           format_options=['suppress_gps'],
           parent=book.subareas['Machete Monkey'],
           description='')
#Fuzzy Dice gps='44.4403, -122.57976'
Formation(name='Deep Sea Diver',
           gps='44.44034, -122.57973',
           format_options=['suppress_gps'],
           parent=book.subareas['Middle Garden'], 
           description='This cool mini cliff band is roughly 25\' tall and features a big crack on the left side. The entire wall seeps and the crack in particular is almost always wet. A variety of lines have been climbed and forgotten on this formation over the years.')
Formation(name='Back Seat Driver',
           gps='44.44042, -122.57952',
           format_options=['suppress_gps'],
           parent=book.subareas['Middle Garden'],
           description='Up the hill and to the right of the Deep Sea Diver Wall')
Formation(name='Jaws',
           gps='44.44021, -122.57969',
           format_options=['suppress_gps'],
           parent=book.subareas['Middle Garden'],
           description='Just down hill from the Deep Sea Diver wall is a boulder with some fun compression on its down hill face.')
Formation(name='Prince Albert',
           gps='44.43993, -122.57947',
           format_options=['suppress_gps'],
           parent=book.subareas['Middle Garden'],
           description='This cool spire is surprisingly hard to see from the road. Several lines have been established and forgotten on all aspects of the pillar. Note that getting off of this rod can be a challenge, either bring a rope and rappel off the bolted anchor or down climb the tall and chossy slab.')
           
Route(name='The Story of O',
      parent=book.formations['The Story of O Boulder'],
      grade=3,
      rating=2,
      description='Sit start on the far left end of the boulder and follow the arête to a rock over jug at the apex.')           
Route(name='Santa Cruz Ski Trip',
      parent=book.formations['The Story of O Boulder'],
      grade=1,
      rating=2,
      description='Sit Start on the low jug ledge in the center of the face and climb straight up to join the top of The Story of O.')
Route(name='wikiFeet',
      parent=book.formations['The Story of O Boulder'],
      grade=0,
      rating=1,
      description='Sit start anywhere on a triangle feature on the right side of the boulder climb straight up.')
Route(name='Loggin Bogs',
      parent=book.formations['Titanium Boulder'],
      FA='Andrew Child',
      grade=6,
      rating=2,
      description='Start Matched on the big rail in the small cave. Work your way right to join up with Häagen Dogs.')
Route(name='Häagen Dogs',
      parent=book.formations['Titanium Boulder'],
      FA='Griffin Thoms',
      grade=5,
      rating=2,
      description='Sit start on the right side of a small cave with your left hand on a flat crimp in the cave and your right hand on a sharp crimp just outside of the cave. Follow the path of least resistance more or less straight up.')
Route(name='Titanium',
      parent=book.formations['Titanium Boulder'],
      grade='7/8',
      rating=2,
      description='Start matched on the lowest left leaning seam and follow a system of lay backs up the center of the face. Difficulty eases after a hard first move.')
Route(name='Foxglove',
      parent=book.formations['Foxglove Boulder'],
      grade=1,
      rating=2,
      description='Scrunchy start with hands matched on loafey ripple. This low ball may be a lot of fun for the shorter folks.')
Route(name='Pumpkin Spice',
      parent=book.formations['Pumpkin'],
      grade='6',
      rating=2,
      name_unconfirmed=True,
      description='Sit start on the left side of the overhang with left hand on a sharp side pull and right hand on the lower of two side pull rails. Trend right along the roof to an easy top out over a sussy landing.')
Route(name='Baseball',
      parent=book.formations['Baseball'],
      grade='3-',
      rating=1,
      description='Sit start with a high left hand on a good dish around the blunt corner and a low right hand '
                  'pinch. Pull a powerful move to good edges and continue straight up.')
Route(name='Bunt',
      parent=book.formations['Baseball'],
      grade=1,
      rating=1,
      description='Sit start with both hands in a low bubbly pod. Climb straight up.')
Route(name='Bread Heel',
      parent=book.formations['Bread Loaf'],
      grade=3,
      rating=1,
      description='Stand start in narrow compression on two big side pulls. Make your way to a big under cling flake and follow it up and left onto the slab.')
Route(name='Bread Loaf Left',
      parent=book.formations['Bread Loaf'],
      grade=4,
      rating=3,
      description='Stand start on two horizontal edges. Navigate your way to some good lumpy jugs midway up the ' 
                  'route and either mantle or side pull your way to the top..')
Route(name='Breadwinner',
      parent=book.formations['Bread Loaf'],
      grade=9,
      rating=3,
      FA='Kalel Chester',
      description='Start as for Bread Loaf Traverse, climb straight up.')
Route(name='Bread Loaf Traverse',
      parent=book.formations['Bread Loaf'],
      grade=5,
      rating=2,
      description='stand start with hands matched in the left of two good pods in the lowest diagonal crack. Follow '
                  'the crack system right with the help of a good hold under the roof. top along the arête. Dabby.')
Route(name='Worf',
      parent=book.formations['Bread Loaf'],
      grade=5,
      rating=2,
      description='Starting from the low horizontal seams crank a few powerful moves to gain a blunt corner. Both sides of the corner are worthwhile and valid top out options, each challenging in its own way.')
Route(name='Scratch and Spliff Traverse',
      parent=book.formations['Scratch and Spliff'],
      grade=3,
      rating=3,
      description='Start at the far right of the major horizontal crack (as for Roach) and traverse all the way left '
                  'topping out along a juggy vertical crack system.')
Route(name='Scratch',
      parent=book.formations['Scratch and Spliff'],
      grade=4,
      rating=2,
      description='Stand start with right hand on a good hold in the horizontal crack and left hand wrapping around '
                  'a juggy corner. Jump to a bubbly rail and tick tack your way to the top. Originally this route '
                  'started as for Scratch and Spliff Traverse.')
Route(name='Spliff',
      parent=book.formations['Scratch and Spliff'],
      grade=3,
      rating=3,
      serious=1,
      description='Start on a large hanging flake. Climb straight up. Sit start seems possible but wouldn\'t add '
                  'much to the experience.')
Route(name='Roach',
      parent=book.formations['Scratch and Spliff'],
      grade=0,
      rating=2,
      description='Stand start with a good edge in the horizontal crack..')
Route(name='For What it\'s Worth',
      parent=book.formations['Scratch and Spliff'],
      grade=2,
      rating=2,
      name_unconfirmed=True,
      description='Squat start on a low ramp on the NW corner of the boulder using a left hand low on the arête and '
                  'a right hand side pull. Bump up the arête then dyno to the lip. Dab potential creates a lot of '
                  'the difficulty.')
Route(name='Caliban\'s War',
      parent=book.formations['Scratch and Spliff'],
      grade=6,
      grade_unconfirmed=True,
      description='Stand start with hand holds in a horizontal crack. Crank one move to the lip. Extremely morpho. ')
Route(name='Stoned Age',
      parent=book.formations['Scratch and Spliff'],
      grade=2,
      grade_unconfirmed=True,
      description='It looks like you could easily climb from the horizontal crack to a diagonal crack on the upper '
                  'right, but the landing is very poor. Older guidebooks indicate that this has been done.')
Route(name='Dr. Strangelove',
      parent=book.formations['Dr. Strangelove'],
      grade=6,
      rating=3,
      serious=1,
      description='Climb the aesthetic arête from the left (right hand on arête) side. The natural landing is heinous, but can be improved by laying logs over the chasm. Also known as "The Hook"')
Route(name='War Room',
      parent=book.formations['Dr. Strangelove'],
      grade=9,
      rating=2,
      grade_unconfirmed=True,
      description='Start with left hand on your choice of holds on a sloper rail, and right hand on a vertical edge. Make a hard-ish move to a decent left hand side pull, then bravely launch for the jug lip over a mediocre landing. A couple holds broke here during a 2019 cleaning, but this route (or something similar) was once known as "Andrew\'s Line" (no, some other Andrew).')
Route(name='Kick It',
      parent=book.formations['Kick It'],
      grade=2,
      rating=2,
      description='Start standing with left hand on a small edge or on the left arête and right hand under cling a big slopey rib. Climb the clean face using both arêtes. Worth doing if you are making the trek out to strange love. Also known as Dishing.')
Route(name='Mega Good Boulder',
      parent=book.formations['Mega Good Boulder'],
      item_id='MGB',
      grade=4,
      rating=1,
      description='Sit start the MGB using single pad edges below the blobby sloper. Harder and weirder than it looks.')
Route(name='Algebra',
      parent=book.formations['Algebra'],
      grade=5,
      rating=1,
      description='Sit start using the detached block. Climb the left arête.')
Route(name='Jugs',
      parent=book.formations['Crack Boulder'],
      grade=0,
      rating=1,
      description='Sit start and climb the short line of jugs to a dirty top out.')
Route(name='Machete Monkey',
      parent=book.formations['Machete Monkey'],
      grade=3,
      rating=1,
      grade_unconfirmed=True,
      description='Climb the left arête of the higher-tiered area to the left of the obvious roof. Fun liebacking from an obvious jug at break')
Route(name='Project',
      item_id='Machete 3',
      parent=book.formations['Machete Monkey'],
      description='A potential line on the downhill side of the Machete Monkey boulder looks very hard and has likely never been climbed before. A new bolted anchor at the top aides projecting.')
Route(name='Little Hesitator',
      parent=book.formations['June 24th'],
      item_id='June 1',
      grade=2,
      rating=2,
      name_unconfirmed=True,
      description='Use any hands you want to start perched on a large protruding foot hold. Technical edging, some small crimps, and maybe a dyno will bring you to the top of this mostly blank slab. This route is much more challenging (and therefore more rewarding) if you are short.')
Route(name='June 24th',
      parent=book.formations['June 24th'],
      grade=7,
      rating=3,
      description='Stand start matched at the bottom of a left facing diagonal rail. A sequence of difficult laybacks gives way to small crimps. This is one of the best lines that the Garden has to offer.')
Route(name='June 69th',
      parent=book.formations['June 24th'],
      grade=3,
      description='An obvious line to the right of the June 24th rail would start in an awkward squat with hands matched on a thin crimp.')
Route(name='Young Ju¢y',
      parent=book.formations['Young Ju¢y'],
      grade=8,
      rating=2,
      description='Climb an arching line left across the lip starting from two right-facing side pull jugs at/below the lip for on the right side of the boulder. This line is certainly one to seek out if you\'re a local, it\'s very uncommon to find pure slopers like these in Oregon.')
Route(name='Loosey Ju¢y',
      parent=book.formations['Young Ju¢y'],
      grade=1,
      rating=2,
      description='Sand start on the lower of two right facing scars. Climbs up a a weird scoop with smear feet.')
Route(name='Duck Hole',
      parent=book.formations['Duck Twirler'],
      item_id='DT 1',
      grade=4,
      rating=1,
      name_unconfirmed=True,
      description='Stand start in a pit using a left hand jug and good right hand side pull pinch. Use techy feet to grab whatever you can on a weirdly smooth bulge and crank to better holds higher up. Harder than you\'d think.')
Route(name='Anti-Tiff',
      parent=book.formations['Duck Twirler'],
      grade=2,
      rating=2,
      description='Stand start and climb the center face however you see fit. This has also been climbed from a low sit start.')
Route(name='Screaming at a Wall',
      parent=book.formations['Duck Twirler'],
      grade=2,
      rating=2,
      description='Stand start with low side pulls in wide compression, a few long moves bring you to a technical mantle at the top. Starting a little higher is also a valid and potentially more enjoyable interpretation.')
Route(name='Duck Twirler',
      parent=book.formations['Duck Twirler'],
      grade=2,
      rating=2,
      description='Sit start in wide compression with right hand on a large vertical rail and left hand on a low side pull. Climb up and right finishing through a cool pinch near the top of the boulder')
Route(name='Deforestation',
      parent=book.formations['Duck Twirler'],
      grade=3,
      rating=3,
      description='Squat start on a pair of sloping rails. A few tensiony moves on good holds get you to the top.')
Route(name='Deep Sea Diver',
      parent=book.formations['Deep Sea Diver'],
      grade='4',
      rating=2,
      description='Starting on a high edge to the left of the crack traverse the base of the cliff left to right. Finish at a high jug ledge on the far right of the cliff or, for style points, rock over onto a no hands rest.')
Route(name='Ya Ya Crack',
      parent=book.formations['Deep Sea Diver'],
      grade='?',
      description='Climb the flaring crack on the left side of the cliff. Maybe better as a TR as the top is a dirty slab and the landing is bad.')
Route(name='Tidal Wave',
      parent=book.formations['Deep Sea Diver'],
      item_id='DSD 3',
      grade=4,
      serious=2,
      name_unconfirmed=True,
      description='Climb the right side of the cliff from an obvious low jug. Be aware that the upper portion of this line is chossy and dirty.')
Route(name='Deep Sea Diver Right',
      parent=book.formations['Deep Sea Diver'],
      item_id='DSD 4',
      grade='?',
      name_unconfirmed=True,
      description='Climb the ledges on the far right of the cliff. For full value this line could be linked into from Deep Sea Diver.')
Route(name='Back Seat Driver',
      parent=book.formations['Back Seat Driver'],
      grade=5,
      grade_unconfirmed=True,
      description='Start matched on a big under cling. Climb the arête on the left side until you gain jugs near the top.')
Route(name='Jaws',
      parent=book.formations['Jaws'],
      grade=5,
      rating=2,
      description='Stand start using the best parts of the two opposed compression arêtes. A few squeezy moves leads to a dabby yoink to a jug followed by a hard to read top out.')
Route(name='Remora',
      parent=book.formations['Jaws'],
      grade=6,
      rating=2,
      name_unconfirmed=True,
      description='Lay down start in compression with your right hand at the bottom of the left hand sloping rib of Jaws and your left hand on a low sloper at the rim of a little alcove. A far away toe hook helps you pull off the ground. Pull a few moves to join the top of Jaws.')           
Route(name='Prince Albert',
      parent=book.formations['Prince Albert'],
      grade="4/5",
      rating=3,
      description='A sequence of balancy moves lead you up the aesthetic trail facing side of the boulder to a mercifully juggy top out. Stand start with left hand on the arête and right hand on a dishy side pull. This route can also been climbed from a variety of sit starts which add a little interest but don\'t have a major influence on the grade. See boulder description for descent beta.') 
Route(name='Things Fall Apart',
      parent=book.formations['Prince Albert'],
      name_unconfirmed=True,
      item_id='PA 2',
      grade='7',
      rating=3,
      serious=1,
      description='Stand start with right hand on the arête and left hand on any of the broken downclings. Climb up the small roof finishing around the center right of the head wall. See boulder description for descent beta.')
Route(name='Easy Up, Easy Down',
      parent=book.formations['Prince Albert'],
      grade=0,
      rating=1,
      serious=2,
      description='Climb the chossy slab. The name is kind of a sandbag because getting down is not that easy.')
      
Variation(name='Arnold Palmer',
          parent=book.routes['Santa Cruz Ski Trip'],
          grade='4/5',
          rating=2,
          description='Link Santa Cruz Ski Trip into wikiFeet without using the arête. Weird but fun.')
Variation(name='Bilbo Baggins',
          parent=book.routes['Loggin Bogs'],
          grade=7,
          rating=2,
          description='Start as for Loggin Bogs but cut back left across the mostly blank lip of the overhang before topping.')
Variation(name='Ice Spice',
          parent=book.routes['Pumpkin Spice'],
          grade='7/8',
          rating=2,
          description='Low start to Pumpkin Spice. Start with a left hand side pull slot and right hand slopey edge. The starting holds for this have been subject to some debate, one ascensionist stresses that its not the true low start unless you are sitting with your butt in the dirt.')
Variation(name='Baker\'s Dozen',
          parent=book.routes['Bread Loaf Traverse'],
          grade='7/8',
          rating=2,
          description='Start as for Bread Loaf Left, traverse into the bread loaf traverse.')
Variation(name='Late Start',
          parent=book.routes['Scratch and Spliff Traverse'],
          grade=2,
          rating=2,
          name_unconfirmed=True,
          description='Sit start with juggy holds at the top of a low ramp. Climb straight up into the top of Scratch '
                      'and Spliff Traverse.')
Variation(name='Machete Man',
          parent=book.routes['Machete Monkey'],
          grade=5,
          rating=0,
          grade_unconfirmed=True,
         description='A mediocre sit start joins Machete Monkey from the hole underneath. Begin with your right hand on the obvious edge and left hand on a low edge around the corner.') 
Variation(name='Machete Monkey Left',
          parent=book.routes['Machete Monkey'],
          grade=1,
          rating=1,
         description='Start on Machete monkey, and bail onto the slab.')     
Variation(name='June 69th High Start',
          parent=book.routes['June 69th'],
          grade=1,
          rating=2,
         description='The top of June 69th is an enjoyable and worthwhile endevor in its own right. Instead of of doing the squanchy the first move of the low start, begin on the high single pad crimps.')     
Variation(name='Deforestation Dyno',
          parent=book.routes['Deforestation'],
          grade=4,
          rating=2,
         description='Skip all the holds and jump all the way to to lip from the start.') 
Variation(name='Juice WRLD',
          parent=book.routes['Young Ju¢y'],
          grade=4,
          rating=2,
         description='Start as for Young Ju¢y but go straight up the slab. Classic!') 
Variation(name='Jenga Crack',
          parent=book.routes['Jugs'],
          item_id='Crack 2',
          grade=2,
          grade_unconfirmed=True,
          name_unconfirmed=True,
          description='Climb the short vertical crack from a sit start. This isn\'t quite a distinct line from Jugs, but eliminating holds could make it more difficult/worthwhile.')
                      
if __name__ == '__main__':
    sys.exit()
