from dataStructure import Photo, Topo, AreaMap, SubAreaMap
from GB_Book import book

Photo(name='Overview',
      file_name='areaOverview.png',
      parent=book,
      size = 'pr',
      loc = 'a',
      format_options=['force_include'],
      #description='Garden areas overview. Parking areas marked in blue.'
      )
Photo(name='Overview2',
      file_name='areaOverview.png',
      parent=book,
      size = 'pr',
      loc = 'a',
      format_options=['force_include'],
      description='Garden areas overview. Parking areas marked in blue.'
      )
Photo(name='Riptide',
      file_name='Riptide.jpg',
      parent=book.formations['Undertow'],
      size = 'h',
      loc = 'e',
      route=book.routes['Riptide'],
      credit='Andrew Child',
      description='Rob on Riptide.')
Photo(name='Fight Club',
      file_name='FightClub2.jpg',
      parent=book.subareas['Fight Club'],
      size='h',
      loc='e',
      route=book.routes['Fight Club'],
      credit='Andrew Child',
      description='Michael near the top of Fight Club.')
      

Topo(name='Baldo',
     parent=book.formations['Baldo'],
     file_name='baldo.svg',
     size='h',
     routes={
         'path600':book.climbs['Frontside Baldo'],
         'path598':book.climbs['Frontside Baldo'],
     })
Topo(name='Berned',
     parent=book.climbs['All Berned Down'],
     file_name='berned.svg',
     size='h',
     routes={
         'path744':book.climbs['All Berned Up'],
         'path742':book.climbs['All Berned Up'],
         'path740':book.climbs['All Berned Down'],
         'path738':book.climbs['All Berned Down'],
     })
Topo(name='Classique',
     parent=book.formations['Classique'],
     file_name='classique.svg',
     size='h',
     routes={
         'path445':book.climbs['Classique'],
         'path391':book.climbs['Classique'],
         'path293':book.climbs['Classique'],
     })
Topo(name='Crazy Cool',
     parent=book.formations['Crazy Cool'],
     file_name='crazyCool.svg',
     size='h',
     routes={
         'path586':book.climbs['Crazy Cool Arête'],
         'path584':book.climbs['Crazy Cool Arête'],
         'path582':book.climbs['Crazy Cool Arête'],
     })
Topo(name='Overhand',
     parent=book.formations['Overhand'],
     file_name='overhand2.svg',
     size='h',
     routes={
         'path1177':book.climbs['Overhand'],
         'path1175':book.climbs['Overhand'],
     })
Topo(name='Hueco Wabo',
     parent=book.formations['Hueco Wabo'],
     file_name='hueco.svg',
     size='h',
     routes={
         'path1918':book.climbs['Hueco Wabo'],
         'path1920':book.climbs['Hueco Wabo'],
     })
Topo(name='Azain Spire',
     parent=book.formations['Azain Spire'],
     file_name='azainSpire.svg',
     size='h',
     routes={
         'path724':book.climbs['Snakes and Martyrs'],
         'path726':book.climbs['Snakes and Martyrs'],
     })
Topo(name='Three Star Ledge',
     parent=book.formations['Three Star Ledge'],
     file_name='threeStar2.svg',
     size='h',
     routes={
         'path2023':book.climbs['Three Star Ledge'],
         'path2021':book.climbs['Three Star Ledge Variation'],
         'path2019':book.climbs['Three Star Ledge Variation'],
         'path2017':book.climbs['Three Star Ledge Variation'],
     })
AreaMap(name='The Garden Main Area Overview',
        parent=book.areas['The Garden Main'],
        file_name='Garden.svg',
        sub_areas={
            'rect2027': book.subareas['Big'],
            'rect1376': book.subareas['Azain'],
            'rect2313': book.subareas['Entrance Area'],
            'rect2908': book.subareas['François'],
            'rect3027': book.subareas['Fight Club'],
            'rect3200': book.subareas['Meth Lab'],
            'rect3386': book.subareas['Undertow'],
            'rect380': book.subareas['Child of God'],
        },
        layers=['Base'],
        size='f',)
AreaMap(name='Armageddon Area Overview',
        parent=book.areas['Upper Garden'],
        file_name='upperGarden.svg',
        sub_areas={
            'rect27128': book.subareas['The Bread Loaves'],
            'rect27051': book.subareas['entranceUpper'],
        },
        layers=['Base', 'border'],
        border='rect27048',
        size='f',)
SubAreaMap(name='Entrance Area map',
           parent=book.subareas['Entrance Area'],
           out_file_name='entrance_c.png',
           file_name='Garden.svg',
           layers=['Entrance', 'Base'],
           border='rect2313',
           routes={
           'path1767':book.climbs['Toilet Bowl Traverse'],
           'path1769':book.climbs['Toilet Bowl'],
           'path1771':book.climbs['Donatello'],
           'path1773':book.climbs['Leonardo'],
           'path1775':book.climbs['Raphael Crack'],
           'path1777':book.climbs['Overhand'],
           'path1779':book.climbs['Three Star Ledge'],
           'path1781':book.climbs['All Sorts of Ease'],
           'path1783':book.climbs['In the Shadow of Giants'],
           'path1785':book.climbs['Tonsil'],
           'path1787':book.climbs['Boys in the Woods'],
           'path1789':book.climbs['Ice Cubes Shiny Jerry Curl'],
           'path1791':book.climbs['Tree Slab'],
           'path2200':book.climbs['Spider Bumps'],
           })
SubAreaMap(name='Fight Club Area map',
           parent=book.subareas['Fight Club'],
           out_file_name='fightClub_c.png',
           file_name='Garden.svg',
           layers=['Fight Club', 'Base'],
           border='rect3027',
           size='f',
           routes={
           'path876':book.climbs['Unknown on E\'s Dirty B'],
           'path874':book.climbs['Green Hell'],
           'path4077':book.climbs['E\'s Dirty B'],
           'path1519':book.climbs['Jim Halpert'],
           'path878':book.climbs['Michael Scott'],
           'path1517':book.climbs['Daryl Philbin'],
           'path1515':book.climbs['Vince'],
           'path1513':book.climbs['The Ear'],
           'path1511':book.climbs['Fight Club 2'],
           'path1509':book.climbs['Project Mayhem'],
           'path1507':book.climbs['Trust'],
           'path1505':book.climbs['Austin Powers'],
           'path1503':book.climbs['Dr. Evil'],
           'path1174':book.climbs['Dwight Schrute'],
           })
SubAreaMap(name='Undertow area map',
           parent=book.subareas['Undertow'],
           out_file_name='undertow_c.png',
           file_name='Garden.svg',
           layers=['Undertow', 'Base'],
           border='rect3386',
           routes={
               'path1244':book.climbs['Silly Steep Mantle'],
               'path1246':book.climbs['Undertow'],
               'path1248':book.climbs['Tidepool'],
               'path1250':book.climbs['Chockstone Highball'],
               'path1252':book.climbs['Car Alarm Traverse'],
               'path1254':book.climbs['2 Ton Chevey'],
               'path1256':book.climbs['Pup Truck'],
               'path1258':book.climbs['Comp Route'],
               'path1260':book.climbs['Panic Button'],
               'path3384':book.climbs['Bubonic Plague'],
               'path872':book.climbs['Hanging Prow Project'],
           })
SubAreaMap(name='Meth Lab area map',
           parent=book.subareas['Meth Lab'],
           out_file_name='methLab_c.png',
           file_name='Garden.svg',
           layers=['Meth Lab', 'Base'],
           border='rect3200',
           routes={
               'path1196':book.climbs['Flesh Bridge'],
               'path771':book.climbs['West Arête'],
               'path521':book.climbs['Southern Discomfort'],
               'path760':book.climbs['Don\'t Blow the Jug'],
               'path762':book.climbs['Trust Issues'],
               'path764':book.climbs['Leave it to Jesus'],
               'path766':book.climbs['Smackdown'],
               'path768':book.climbs['Heisenburg'],
               'path770':book.climbs['Guillotine'],
               'path772':book.climbs['Octernal'],
               'path774':book.climbs['Two Blows One Stroke'],
               'path776':book.climbs['E\'s'],
               'path778':book.climbs['Enchilada'],
               'path780':book.climbs['Swollen Member'],
               'path782':book.climbs['Meth Lab Highball'],
               'path784':book.climbs['The Bubbler'],
               'path4341':book.climbs['Meth Lab Project'],
               'path426':book.climbs['Slam Dunk'],
               'path428':book.climbs['Gargoyle'],
               'path1731':book.climbs['Chillum'],
           })
SubAreaMap(name='Big area map',
           parent=book.subareas['Big'],
           out_file_name='big_c.png',
           file_name='Garden.svg',
           routes={
               'path5664':book.climbs['Frontside Baldo'],
               'path5662':book.climbs['Hueco Wabo'],
               'path5660':book.climbs['All Berned Up'],
               'path410':book.climbs['Mini Hydro Tube'],
               'path5658':book.climbs['Bitchin Corners'],
               'path5658-4':book.climbs['Smol'],
               'path880':book.climbs['Cargo Net Project'],
               'path1395':book.climbs['Classique'],
               'path1397':book.climbs['Crazy Cool Arête'],
           },
           layers=['Big', 'Base'],
           border='rect2027'),
SubAreaMap(name='Azain area map',
           parent=book.subareas['Azain'],
           out_file_name='azain_c.png',
           file_name='Garden.svg',
           size='h',
           routes={
               'path720':book.climbs['Ground up Blowie'],
               'path718':book.climbs['Nightcrawler'],
               'path716':book.climbs['The Good Slab'],
               'path714':book.climbs['The Good'],
               'path712':book.climbs['Another'],
               'path710':book.climbs['Snakes and Martyrs'],
               'path708':book.climbs['Next to the Good'],
               'path740':book.climbs['Into the Light'],
               'path742':book.climbs['Garden Groove'],
               'path1962':book.climbs['Simpson\'s First'],
           },
           layers=['Azain', 'Base'],
           border='rect1376')
SubAreaMap(name='Child of God area map',
           parent=book.subareas['Child of God'],
           out_file_name='child_o_god_c.png',
           file_name='Garden.svg',
           size='f',
           routes={
               'ellipse374':book.climbs['Gumby Crack'],
               'circle372':book.climbs['Gumby Slab'],
               'circle370':book.climbs['Gumby Arête'],
               'ellipse368':book.climbs['The Siren'],
               'ellipse366':book.climbs['Garden Variety'],
               'ellipse364':book.climbs['The Arboretum'],
               'ellipse362':book.climbs['Full Stroke'],
               'ellipse360':book.climbs['Philanthropy'],
               'circle358':book.climbs['Locksmith'],
               'path1391':book.climbs['Oregon Arête'],
           },
           layers=['Child of God', 'Base'],
           border='rect380')
SubAreaMap(name='François area map',
           parent=book.subareas['François'],
           out_file_name='Big Frank_c.png',
           file_name='Garden.svg',
           layers=['Big Fred', 'Base'],
           border='rect2908',
           routes={
               'path1194':book.climbs['Fern Sully'],
               'path714-5':book.climbs['Scary Grandma'],
               'path712-7':book.climbs['Angry Mom'],
               'path712-6':book.climbs['Easy Grandma'],
               'path710-5':book.climbs['François'],
               'path1964':book.climbs['Geodesic Weiner'],
               'path1966':book.climbs['Shake it Out Frank'],
           })
SubAreaMap(name='Pink Tag area map',
           parent=book.areas['Pink Tag Boulders'],
           out_file_name='Pink Tag_c.png',
           file_name='Garden.svg',
           size='f',
           layers=['Pink Tag', 'Base'],
           border='rect3553',
           routes={
               'path3723':book.climbs['Farley Prep'],
               'path3721':book.climbs['Le Lemét'],
               'path3719':book.climbs['Belushi'],
               'path3717':book.climbs['Frat House'],
               'path3715':book.climbs['Workshop 68'],
               'path3713':book.climbs['Territorial Pissings'],
           })
SubAreaMap(name='Entrance area map',
           parent=book.subareas['entranceUpper'],
           out_file_name='entranceUpper_c.png',
           file_name='upperGarden.svg',
           layers=['Entrance', 'Base'],
           border='rect27051',
           routes={
               'path27105':book.climbs['Pumpkin Spice'],
               'path27107':book.climbs['Baseball'],
               'path27109':book.climbs['Bunt'],
           })
SubAreaMap(name='Bread loaf/Scratch and Spliff area map',
           parent=book.subareas['The Bread Loaves'],
           out_file_name='bread_c.png',
           file_name='upperGarden.svg',
           layers=['Bread', 'Base'],
           border='rect27128',
           size='f',
           routes={
               'path27126':book.climbs['Caliban\'s War'],
               'path27124':book.climbs['Scratch'],
               'path27122':book.climbs['Spliff'],
               'path27120':book.climbs['Scratch and Spliff Traverse'],
               'path27118':book.climbs['For What it\'s Worth'],
               'path27116':book.climbs['Worf'],
               'path27114':book.climbs['Bread Loaf Traverse'],
               'path27112':book.climbs['Bread Loaf Left'],
           })
SubAreaMap(name='Redneck Riviera area map',
           parent=book.subareas['Redneck Riviera'],
           file_name='redneck.svg',
           layers=['Redneck', 'Base'],
           border='rect3479',
           size='h',
           routes={
               'path3423':book.climbs['Pony Boy'],
               'path3421':book.climbs['Monorail'],
               'path3419':book.climbs['Ugly Face'],
               'path3417':book.climbs['Binding of Isaac'],
               'path3415':book.climbs['Moss Boss'],
               'path3413':book.climbs['Chicken Tendies'],
               'path3411':book.climbs['Teenage Libertarians'],
               'path3357':book.climbs['Falcon\'s Reach'],
           })
           
           
if __name__ == '__main__':
    sys.exit()