from dataStructure import Photo, Topo, AreaMap, SubAreaMap
from GB_Book import book


Photo(name='Overview',
      file_name='areaOverview.png',
      parent=book,
      size = 'pr',
      loc = 'a',
      format_options=['force_include'],
      description='Garden areas overview. Parking areas marked in dark blue.'
      )
Photo(name='Riptide',
      file_name='Riptide.jpg',
      parent=book.formations['Undertow'],
      size = 'h',
      loc = 'e',
      route=book.routes['Riptide'],
      credit='Andrew Child',
      description='Rob on Riptide.')
Photo(name='Fight Club',
      file_name='FightClub2.jpg',
      parent=book.subareas['Fight Club'],
      size='h',
      loc='e',
      route=book.routes['Fight Club'],
      credit='Andrew Child',
      description='Michael near the top of Fight Club.')
Photo(name='Octernal',
      file_name='Octurnal.jpg',
      parent=book.subareas['Undertow'],
      size='s',
      loc='e',
      route=book.routes['Octernal'],
      credit='Andrew Child',
      description='Carson landing the big throw on Octernal. Classic!')
Photo(name='Smackdown',
      file_name='Smackdown.jpg',
      parent=book.subareas['François'],
      route=book.routes['Smackdown'],
      size='f',
      loc='e',
      credit='Carson Dension',
      description='Andrew posting up at the start of Smackdown.')
Photo(name='Ground up Blowie',
      file_name='blowie.jpg',
      parent=book.formations['Toilet Bowl'],
      size='p',
      loc='e',
      route=book.routes['Ground up Blowie'],
      credit='Michael Gardener Brown',
      description='Andrew struggling to find a finger lock on Ground up Blowie.')
Photo(name='Butterfly',
      file_name='butterfly.jpg',
      parent=book.subareas['The Garden Cliff'],
      size='f',
      loc='e',
      route=book.routes['Butterfly Effect'],
      credit='Andrew Child',
      description='Griffin on Butterfly Effect.')
Photo(name='2blows',
      file_name='2blows.jpg',
      parent=book.subareas['Azain'],
      size='h',
      loc='e',
      route=book.routes['Two Blows One Stroke'],
      credit='Andrew Child',
      description='Griffin on Two Blows One Stroke.')         
Photo(name='pinkTag',
      file_name='pinkTagSign.jpg',
      parent=book.subareas['Pink Tag'],
      size='h',
      format_options=['force_include'],
      description='All but one of the climbs in this area are downhill of this sign.')      
Photo(name='needles',
      file_name='needles.jpg',
      parent=book.subareas['The Needles'],
      size='f',
      format_options=['force_include'],
      description='The Needles as seen from NF-1133.')      
Photo(name='pinnacle',
      file_name='pinnacle.jpg',
      parent=book.subareas['Santiam Pinnacle'],
      size='h',
      format_options=['force_include'],
      description='Santiam Pinnacle as seen from the road.')      
Photo(name='Cascadia',
      file_name='CascadiaCave2.jpg',
      parent=book.subareas['Cascadia Cave'],
      size='h',
      format_options=['force_include'],
      description='This is a cultural site. Do not climb here.')      


Topo(name='Bitchin Corners',
     parent=book.formations['Bitchin Corners'],
     file_name='bitchin.svg',
     size='h',
      loc='e',
     border='rect362',
     routes={
         'path368':book.climbs['Left Corner'],
         'path314':book.climbs['Left Corner'],
         'path1002':book.climbs['Bitchin Corners'],
         'path1029':book.climbs['Bitchin Corners'],
         'path551':book.climbs['Bitchin Arête'],
         'path450':book.climbs['Bitchin Arête'],
         'path1014':book.climbs['Bitchin Corners Sit'],
         'path1031':book.climbs['Bitchin Corners Sit'],
     })
Topo(name='Baldo',
     parent=book.formations['Baldo'],
     file_name='baldo.svg',
     size='h',
     routes={
         'path600':book.climbs['Frontside Baldo'],
         'path598':book.climbs['Frontside Baldo'],
     })
Topo(name='Berned',
     parent=book.climbs['All Berned Down'],
     file_name='berned.svg',
     size='h',
     routes={
         'path744':book.climbs['All Berned Up'],
         'path742':book.climbs['All Berned Up'],
         'path740':book.climbs['All Berned Down'],
         'path738':book.climbs['All Berned Down'],
     })
Topo(name='bigSlab',
     parent=book.climbs['Slabarific'],
     file_name='bigSlab.svg',
     size='h',
     border='rect291',
     routes={
         'path507':book.climbs['Pockets'],
         'path505':book.climbs['Pockets'],
         'path454':book.climbs['Pockets'],
         'path509':book.climbs['Big Slab Right'],
         'path452':book.climbs['Big Slab Right'],
         'path450':book.climbs['Slabarific'],
         'path347':book.climbs['Slabarific'],
     })
Topo(name='hydro',
     parent=book.climbs['Mini Hydrotube'],
     file_name='hydro.svg',
     size='h',
     border='rect652',
     routes={
         'path656':book.climbs['Mini Hydrotube'],
         'path654':book.climbs['Mini Hydrotube'],
     })
Topo(name='Classique',
     parent=book.formations['Classique'],
     file_name='classique.svg',
     size='h',
     routes={
         'path445':book.climbs['Classique'],
         'path391':book.climbs['Classique'],
         'path293':book.climbs['Classique'],
     })
Topo(name='Crazy Cool',
     parent=book.formations['Crazy Cool'],
     file_name='crazyCool.svg',
     size='h',
     routes={
         'path586':book.climbs['Crazy Cool Arête'],
         'path584':book.climbs['Crazy Cool Arête'],
         'path582':book.climbs['Crazy Cool Arête'],
     })
Topo(name='Overhand',
     parent=book.formations['Overhand'],
     file_name='overhand2.svg',
     size='h',
     routes={
         'path1177':book.climbs['Overhand'],
         'path1175':book.climbs['Overhand'],
         'path470':book.climbs['Goose Egg'],
         'path416':book.climbs['Goose Egg'],
         'path414':book.climbs['Goose Egg'],
     })
Topo(name='Hueco Wabo',
     parent=book.formations['Hueco Wabo'],
     file_name='hueco.svg',
     size='h',
     routes={
         'path1918':book.climbs['Hueco Wabo'],
         'path1920':book.climbs['Hueco Wabo'],
     })
Topo(name='Azain Spire',
     parent=book.formations['Azain Spire'],
     file_name='azainSpire.svg',
     size='h',
     routes={
         'path724':book.climbs['Snakes and Martyrs'],
         'path726':book.climbs['Snakes and Martyrs'],
     })
Topo(name='Three Star Ledge',
     parent=book.formations['Three Star Ledge'],
     file_name='threeStar2.svg',
     size='h',
     routes={
         'path2023':book.climbs['Three Star Ledge'],
         'path2017':book.climbs['Three Star Ledge'],
     })
Topo(name='The Good',
     parent=book.routes['The Good'],
     file_name='good.svg',
     size='f',
     routes={
         'path1453':book.climbs['The Good'],
         'path1459':book.climbs['The Good'],
         'path1451':book.climbs['Another'],
         'path1457':book.climbs['Another'],
         'path1445':book.climbs['Next to the Good'],
         'path1447':book.climbs['Next to the Good'],
         'path1449':book.climbs['Next to the Good'],
         'path1455':book.climbs['The Good Slab'],
         'path1461':book.climbs['The Good Slab'],
     })
Topo(name='Fight Club Right Side',
     parent=book.formations['Fight Club'],
     file_name='fightClub.svg',
     size='h',
     border='rect789',
     routes={
         'path735':book.climbs['Fight Club 2'],
         'path733':book.climbs['Fight Club 2'],
         'path731':book.climbs['The Ear'],
         'path729':book.climbs['The Ear'],
         'path727':book.climbs['Fight Club'],
         'path725':book.climbs['Fight Club'],
     })
Topo(name='Fight Club Left Side',
     parent=book.routes['Fight Club 2'],
     file_name='fightClub2.svg',
     size='h',
     routes={
         'path1297':book.climbs['Fight Club 2'],
         'path1303':book.climbs['Fight Club 2'],
         'path1299':book.climbs['Fight Club'],
         'path1301':book.climbs['Fight Club'],
         'path1293':book.climbs['Brewmaster'],
         'path1305':book.climbs['Brewmaster'],
     })
Topo(name='E\'s Dirty B',
     parent=book.formations['E\'s Dirty B'],
     file_name='eDirty.svg',
     size='h',
     routes={
         'path446':book.climbs['Green Hell'],
         'path290':book.climbs['Green Hell'],
         'path1003':book.climbs['E\'s Dirty B'],
         'path1005':book.climbs['E\'s Dirty B'],
         'path444':book.climbs['Unknown on E\'s Dirty B'],
         'path388':book.climbs['Unknown on E\'s Dirty B'],
     })
Topo(name='Car Alarm Downhill Side',
     parent=book.routes['White Rhino'],
     file_name='carAlarm.svg',
     size='f',
     routes={
         'path674':book.climbs['Car Alarm Traverse'],
         'path676':book.climbs['Car Alarm Traverse'],
         'path670':book.climbs['White Rhino'],
         'path678':book.climbs['White Rhino'],
         'path668':book.climbs['2 Ton Chevy'],
         'path680':book.climbs['2 Ton Chevy'],
         'path666':book.climbs['Pup Truck'],
         'path682':book.climbs['Pup Truck'],
     })
Topo(name='Car Alarm Uphill Side',
     parent=book.routes['Comp Route'],
     file_name='carAlarm2.svg',
     size='h',
     routes={
         'path824':book.climbs['Comp Route'],
         'path863':book.climbs['Comp Route'],
         'path851':book.climbs['Panic Button'],
         'path861':book.climbs['Panic Button'],
         'path857':book.climbs['Panic Button Variation'],
         'path859':book.climbs['Panic Button Variation'],
     })
Topo(name='Boys in the Woods',
     parent=book.formations['Boys In the Woods'],
     file_name='BITW.svg',
     size='f',
     routes={
         'path1322':book.climbs['Tabor Tots'],
         'path1320':book.climbs['Tabor Tots'],
         'path300':book.climbs['Boys in the Woods'],
         'path458':book.climbs['Boys in the Woods'],
         'path1485':book.climbs['Cuba Gooding'],
         'path460':book.climbs['Cuba Gooding'],
         'path400':book.climbs['Ice Cubes Shiny Jerry Curl'],
         'path462':book.climbs['Ice Cubes Shiny Jerry Curl'],
         'path404':book.climbs['Tree Slab'],
         'path464':book.climbs['Tree Slab'],
         'path480':book.climbs['EZe'],
         'path426':book.climbs['EZe'],
     })
Topo(name='Turd Party',
     parent=book.formations['Party Boulder'],
     file_name='turdParty.svg',
     size='h',
     border='rect1578',
     routes={
         'path1524':book.climbs['Turd Party UR Invited'],
         'path1522':book.climbs['Turd Party UR Invited'],
         'path1520':book.climbs['Turd Party UR Invited'],
     })
Topo(name='E7',
     parent=book.routes['E\'s'],
     file_name='E7.svg',
     size='h',
     routes={
         'path1378':book.climbs['E\'s'],
         'path1376':book.climbs['E\'s'],
         'path1380':book.climbs['E\'s Sit Start Project'],
         'path1382':book.climbs['E\'s Sit Start Project'],
     })
Topo(name='enchilada',
     parent=book.routes['Enchilada'],
     file_name='enchilada2.svg',
     size='h',
     routes={
         'path2078':book.climbs['Enchilada'],
         'path2076':book.climbs['Enchilada'],
         'path2086':book.climbs['Enchilada Left Project'],
         'path2084':book.climbs['Enchilada Left Project'],
         'path2082':book.climbs['Enchilada Low Start Project'],
         'path2080':book.climbs['Enchilada Low Start Project'],
     })
Topo(name='little enchilada',
     parent=book.routes['Little Enchilada'],
     file_name='littleEnchilada.svg',
     size='h',
     border='rect1403',
     routes={
         'path1349':book.climbs['Little Enchilada'],
         'path1347':book.climbs['Little Enchilada'],
     })
Topo(name='Slam dunk',
     parent=book.routes['Slam Dunk'],
     file_name='eboulder2.svg',
     size='h',
     routes={
         'path623':book.climbs['Layup'],
         'path569':book.climbs['Layup'],
         'path1489':book.climbs['Slam Dunk'],
         'path1487':book.climbs['Slam Dunk'],
         'path474':book.climbs['Baller'],
         'path472':book.climbs['Baller'],
         'path418':book.climbs['Baller'],
         'path416':book.climbs['Baller'],
     })
Topo(name='Gargoyle',
     parent=book.formations['E\'s Boulder'],
     file_name='eboulder3.svg',
     size='h',
     border='rect292',
     routes={
         'path1625':book.climbs['Gargoyle'],
         'path1627':book.climbs['Gargoyle'],
         'path1631':book.climbs['Gargoyle Direct'],
         'path1629':book.climbs['Gargoyle Direct'],
         'path1635':book.climbs['Slam Dunk'],
         'path1633':book.climbs['Slam Dunk'],
         'path625':book.climbs['Layup'],
         'path627':book.climbs['Layup'],
     })
Topo(name='Bubonic Plague',
     parent=book.formations['Bubonic Plague'],
     file_name='koan.svg',
     size='h',
     routes={
         'path1777':book.climbs['Bubonic Plague'],
         'path1775':book.climbs['Bubonic Plague'],
     })
Topo(name='Nightcrawler',
     parent=book.formations['Nightcrawler'],
     file_name='nightCrawler.svg',
     size='h',
     routes={
         'path1342':book.climbs['Nightcrawler'],
         'path1396':book.climbs['Nightcrawler'],
     })
Topo(name='Azain',
     parent=book.routes['Garden Groove'],
     file_name='azainCrack.svg',
     size='h',
     routes={
         'path445':book.climbs['Sometimes'],
         'path391':book.climbs['Sometimes'],
         'path447':book.climbs['Garden Groove'],
         'path293':book.climbs['Garden Groove'],
         'path1282':book.climbs['Brontosaurus'],
         'path1280':book.climbs['Brontosaurus'],
     })
Topo(name='Blowie',
     parent=book.formations['Azain'],
     file_name='blowie.svg',
     size='h',
     routes={
         'path527':book.climbs['Ground up Blowie'],
         'path473':book.climbs['Ground up Blowie'],
         'path1143':book.climbs['Piranesi'],
         'path1045':book.climbs['Piranesi'],
     })
Topo(name='Bubbler',
     parent=book.formations['The Bubbler'],
     file_name='bubbler.svg',
     size='h',
     border='rect1186',
     routes={
         'path1132':book.climbs['Chillum Sit'],
         'path1081':book.climbs['Chillum Sit'],
         'path1079':book.climbs['Chillum'],
         'path1077':book.climbs['Chillum'],
         'path1075':book.climbs['The Bubbler'],
         'path419':book.climbs['The Bubbler'],
     })
Topo(name='Jesus',
     parent=book.formations['Meth Lab'],
     file_name='jesus.svg',
     size='f',
     routes={
         'path1908':book.climbs['Don\'t Blow the Jug'],
         'path1910':book.climbs['Don\'t Blow the Jug'],
         'path1906':book.climbs['Trust Issues'],
         'path1912':book.climbs['Trust Issues'],
         'path1902':book.climbs['Leave it to Jesus'],
         'path1916':book.climbs['Leave it to Jesus'],
         'path1904':book.climbs['Leave it to Jesus Sit Start'],
         'path1914':book.climbs['Leave it to Jesus Sit Start'],
         'path736':book.climbs['Leave it to Jesus Left'],
         'path734':book.climbs['Leave it to Jesus Left'],
     })
Topo(name='Methlab Backside',
     parent=book.routes['Octernal'],
     file_name='Methlab.svg',
     size='pr',
     loc = 'e',
     border='rect306',
     routes={
         'path1874':book.climbs['Smackdown'],
         'path1856':book.climbs['Smackdown'],
         'path1876':book.climbs['Harbor Freight'],
         'path1856-2':book.climbs['Harbor Freight'],
         'path921':book.climbs['Harbor Freight Right Exit'],
         'path919':book.climbs['Harbor Freight Right Exit'],
         'path1878':book.climbs['Heisenburg'],
         'path1858':book.climbs['Heisenburg'],
         'path1880':book.climbs['Learys Lunge'],
         'path1860':book.climbs['Learys Lunge'],
         'path1886':book.climbs['Octernal'],
         'path1864':book.climbs['Octernal'],
         'path1884':book.climbs['Guillotine'],
         'path1866':book.climbs['Guillotine'],
         'path1888':book.climbs['Octernal Center Exit'],
         'path1868':book.climbs['Octernal Center Exit'],
         'path1890':book.climbs['Octernal Direct Exit'],
         'path1862':book.climbs['Octernal Direct Exit'],
         'path1892':book.climbs['E\'s'],
         'path1872':book.climbs['E\'s'],
         'path1042':book.climbs['E\'s Sit Start Project'],
         'path1039':book.climbs['E\'s Sit Start Project'],
     })
Topo(name='octernal2',
     parent=book.routes['Two Blows One Stroke'],
     file_name='octurnal2.svg',
     size='h',
     routes={
         'path3604':book.climbs['Two Blows One Stroke'],
         'path3553':book.climbs['Octernal Direct Exit'],
         'path3608':book.climbs['Two Blows One Stroke'],
         'path3606':book.climbs['Octernal Direct Exit'],
     })
Topo(name='Locksmith',
     parent=book.formations['Locksmith'],
     file_name='hula.svg',
     size='h',
     routes={
         'path888':book.climbs['Philanthropy'],
         'path886':book.climbs['Philanthropy'],
         'path883':book.climbs['Brain Hemorrhage'],
         'path879':book.climbs['Brain Hemorrhage'],
         'path881':book.climbs['Locksmith'],
         'path877':book.climbs['Locksmith'],
     })
Topo(name='Philanthropy',
     parent=book.routes['Philanthropy'],
     file_name='philanthropy.svg',
     size='h',
     routes={
         'path1321':book.climbs['Brain Hemorrhage'],
         'path1319':book.climbs['Brain Hemorrhage'],
         'path1317':book.climbs['Philanthropy'],
         'path1315':book.climbs['Philanthropy'],
         'path1313':book.climbs['Philanthropy']
     })
Topo(name='arboretum2',
     parent=book.routes['Garden Variety'],
     file_name='childOfGod.svg',
     size='pr',
     border='rect1172',
     routes={
         'path1920':book.climbs['Sebulba'],
         'path1915':book.climbs['Sebulba'],
         'path1917':book.climbs['Eurovision'],
         'path1913':book.climbs['Eurovision'],
         'path1492':book.climbs['Gumby Arête'],
         'path1490':book.climbs['Gumby Arête'],
         'path1488':book.climbs['Bag of Tricks'],
         'path1486':book.climbs['Bag of Tricks'],
         'path1484':book.climbs['The Siren'],
         'path1482':book.climbs['The Siren'],
         'path1480':book.climbs['Somewhere In-Between'],
         'path1478':book.climbs['Somewhere In-Between'],
         'path1476':book.climbs['Somewhere In-Between'],
         'path1474':book.climbs['The Other Berned'],
         'path1472':book.climbs['The Other Berned'],
         'path1470':book.climbs['The Arboretum'],
         'path1468':book.climbs['The Arboretum'],
         'path1466':book.climbs['The Arboretum'],
         'path1464':book.climbs['Garden Project'],
         'path1462':book.climbs['Garden Project'],
         'path1460':book.climbs['Garden Variety'],
         'path903':book.climbs['Garden Variety'],
     })
Topo(name='Chock Stone',
     parent=book.formations['Chock Stone Highball'],
     file_name='chockstone.svg',
     size='h',
     routes={
         'path1669':book.climbs['Chock Stone Highball'],
         'path1667':book.climbs['Chock Stone Highball'],
     })
Topo(name='All Sorts of Ease',
     parent=book.formations['All Sorts of Ease'],
     file_name='ease.svg',
     size='h',
     routes={
         'path1938':book.climbs['In the Shadow of Giants'],
         'path1936':book.climbs['In the Shadow of Giants'],
         'path1934':book.climbs['All Sorts of Ease'],
         'path1932':book.climbs['All Sorts of Ease'],
     })
Topo(name='scaryGrandma',
     parent=book.routes['Scary Grandma'],
     file_name='scaryGrandma.svg',
     size='h',
     routes={
         'path609':book.climbs['Scary Grandma'],
         'path603':book.climbs['Scary Grandma'],
         'path611':book.climbs['Angry Mom'],
         'path605':book.climbs['Angry Mom'],
         'path613':book.climbs['Easy Grandma'],
         'path607':book.climbs['Easy Grandma'],
     })
Topo(name='scaryGrandma2',
     parent=book.formations['Scary Grandma'],
     file_name='angryMom.svg',
     size='h',
     routes={
         'path447':book.climbs['Easy Grandma'],
         'path391':book.climbs['Easy Grandma'],
         'path445':book.climbs['Angry Mom'],
         'path293':book.climbs['Angry Mom'],
     })
Topo(name='Mini Me',
     parent=book.formations['Mini Me'],
     file_name='miniMe.svg',
     size='h',
     border='rect505',
     routes={
         'path451':book.climbs['Austin Powers'],
         'path449':book.climbs['Austin Powers'],
         'path447':book.climbs['Austin Powers'],
         'path445':book.climbs['Mini Me'],
         'path391':book.climbs['Mini Me'],
         'path293':book.climbs['Mini Me'],
     })
Topo(name='Mini Me 2',
     parent=book.routes['Dr. Evil'],
     file_name='drEvil.svg',
     size='h',
     border='rect561',
     routes={
         'path453':book.climbs['Austin Powers'],
         'path451':book.climbs['Austin Powers'],
         'path449':book.climbs['Mr. Bigglesworth'],
         'path351':book.climbs['Mr. Bigglesworth'],
         'path349':book.climbs['Dr. Evil'],
         'path295':book.climbs['Dr. Evil'],
         'path293':book.climbs['Dr. Evil'],
     })
Topo(name='Office',
     parent=book.formations['Crash Test Dummies'],
     file_name='office.svg',
     size='f',
     border='rect568',
     routes={
         'path460':book.climbs['Dwight Schrute'],
         'path458':book.climbs['Dwight Schrute'],
         'path456':book.climbs['Jim Halpert'],
         'path454':book.climbs['Jim Halpert'],
         'path452':book.climbs['Michael Scott'],
         'path351':book.climbs['Michael Scott'],
         'path449':book.climbs['Daryl Philbin'],
         'path349':book.climbs['Daryl Philbin'],
         'path347':book.climbs['Vince'],
         'path293':book.climbs['Vince'],
     })
Topo(name='Swollen Member',
     parent=book.formations['Swollen Member'],
     file_name='swollen2.svg',
     size='h',
     routes={
         'path1813':book.climbs['Meth Lab Highball'],
         'path2042':book.climbs['Meth Lab Highball'],
         'path1830':book.climbs['Meth Lab Highball Sit Start'],
         'path2040':book.climbs['Meth Lab Highball Sit Start'],
         'path1832':book.climbs['Meth Lab Highball Right'],
         'path2044':book.climbs['Meth Lab Highball Right'],
         'path1760':book.climbs['Swollen Member'],
         'path1811':book.climbs['Swollen Member'],
         'path2046':book.climbs['Swollen Member'],
     })
Topo(name='Fern Sully',
     parent=book.formations['Fern Sully'],
     file_name='fern.svg',
     size='h',
     routes={
         'path445':book.climbs['Fern Sully'],
         'path391':book.climbs['Fern Sully'],
         'path293':book.climbs['Fern Sully'],
     })
Topo(name='Southern Discomfort',
     parent=book.formations['Meth Lab'],
     file_name='soDisco.svg',
     size='h',
     loc='e',
     border='rect646',
     routes={
         'path592':book.climbs['West Arête'],
         'path590':book.climbs['West Arête'],
         'path588':book.climbs['Southern Discomfort'],
         'path586':book.climbs['Southern Discomfort'],
         'path584':book.climbs['Southern Discomfort Direct'],
         'path582':book.climbs['Southern Discomfort Direct'],
     })
Topo(name='Toilet Bowl',
     parent=book.formations['Toilet Bowl'],
     file_name='toilet.svg',
     size='h',
     routes={
         'path1036':book.climbs['Toilet Bowl Traverse'],
         'path1034':book.climbs['Toilet Bowl Traverse'],
         'path1026':book.climbs['Toilet Bowl'],
         'path1024':book.climbs['Toilet Bowl'],
     })
Topo(name='Tonsil',
     parent=book.routes['Tonsil'],
     file_name='tonsil2.svg',
     size='h',
     routes={
         'path2317':book.climbs['Gingiva'],
         'path2315':book.climbs['Gingiva'],
         'path2313':book.climbs['Prowed'],
         'path2311':book.climbs['Prowed'],
         'path2309':book.climbs['Tonsil'],
         'path2307':book.climbs['Tonsil'],
         'path2305':book.climbs['Tonsil'],
     })
Topo(name='Geodesic Wiener',
     parent=book.formations['François'],
     file_name='weiner.svg',
     size='h',
     routes={
         'path2460':book.climbs['Geodesic Wiener'],
         'path2458':book.climbs['Geodesic Wiener'],
         'path995':book.climbs['Geodong'],
         'path290':book.climbs['Geodong'],
         'path999':book.climbs['Pseudorapidity'],
         'path997':book.climbs['Pseudorapidity'],
     })
Topo(name='Trust',
     parent=book.formations['Trust'],
     file_name='trust.svg',
     size='f',
     border='rect1523',
     routes={
         'path678':book.climbs['Trust'],
         'path830':book.climbs['Trust'],
         'path776':book.climbs['Iron Cross'],
         'path832':book.climbs['Iron Cross'],
         'path834':book.climbs['Project Mayhem'],
         'path836':book.climbs['Project Mayhem'],
         'path838':book.climbs['Tyler Durten Dyno'],
         'path840':book.climbs['Tyler Durten Dyno'],
         'path298':book.climbs['Angel Face'],
         'path410':book.climbs['Angel Face'],
         'path302':book.climbs['Durten Layback'],
         'path412':book.climbs['Durten Layback'],
     })
Topo(name='Turtle',
     parent=book.formations['Turtle Shell Boulder'],
     file_name='turtle.svg',
     size='h',
     routes={
         'path855':book.climbs['Raphael Crack'],
         'path861':book.climbs['Raphael Crack'],
         'path857':book.climbs['Donatello'],
         'path863':book.climbs['Donatello'],
         'path859':book.climbs['Leonardo'],
         'path919':book.climbs['Leonardo'],
         'path294':book.climbs['Turtle Traverse'],
         'path1065':book.climbs['Turtle Traverse'],
     })
Topo(name='Undertow',
     parent=book.routes['Undertow'],
     file_name='undertow.svg',
     size='h',
     routes={
         'path1199':book.climbs['Spray Skirt'],
         'path1201':book.climbs['Spray Skirt'],
         'path1097':book.climbs['Undertow'],
         'path1111':book.climbs['Undertow'],
         'path1099':book.climbs['Spray Against the Undertow'],
         'path1105':book.climbs['Spray Against the Undertow'],
         'path1101':book.climbs['Undertow Sit Start'],
         'path1107':book.climbs['Undertow Sit Start'],
         'path1103':book.climbs['Riptide'],
         'path1109':book.climbs['Riptide'],
     })
Topo(name='Undertow2',
     parent=book.formations['Undertow'],
     file_name='undertow2.svg',
     size='f',
     routes={
         'path932':book.climbs['Silly Steep Mantle'],
         'path942':book.climbs['Silly Steep Mantle'],
         'path938':book.climbs['Undertow'],
         'path946':book.climbs['Undertow'],
         'path934':book.climbs['Spray Against the Undertow'],
         'path944':book.climbs['Spray Against the Undertow'],
         'path936':book.climbs['Undertow Sit Start'],
         'path950':book.climbs['Undertow Sit Start'],
         'path1134':book.climbs['Riptide'],
         'path948':book.climbs['Riptide'],
         'path940':book.climbs['Tidepool'],
         'path952':book.climbs['Tidepool'],
         'path1309':book.climbs['Simple Math'],
         'path1305':book.climbs['Simple Math'],
         'path1307':book.climbs['Shake it Out'],
         'path748':book.climbs['Shake it Out'],
     })
Topo(name='François',
     parent=book.routes['François'],
     file_name='frank.svg',
     size='h',
     loc='e',
     routes={
         'path2390':book.climbs['François'],
         'path2388':book.climbs['François'],
         'path1192':book.climbs['Schrödinger Project'],
         'path1190':book.climbs['Schrödinger Project'],
     })
Topo(name='Oregon Arête',
     parent=book.formations['Garden Roof'],
     file_name='oregonArete.svg',
     size='h',
     routes={
         'path742':book.climbs['Full Stroke'],
         'path737':book.climbs['Full Stroke'],
         'path739':book.climbs['Dream Weaver'],
         'path735':book.climbs['Dream Weaver'],
         'path733':book.climbs['Oregon Arête'],
         'path731':book.climbs['Oregon Arête'],
         'path729':book.climbs['Oregon Arête'],
     })
Topo(name='Full Stroke',
     parent=book.routes['Full Stroke'],
     file_name='fullStroke.svg',
     size='h',
     border='rect444',
     routes={
         'path1215':book.climbs['Sebulba'],
         'path1207':book.climbs['Sebulba'],
         'path1212':book.climbs['Eurovision'],
         'path1205':book.climbs['Eurovision'],
         'path1217':book.climbs['Dream Weaver'],
         'path1203':book.climbs['Dream Weaver'],
         'path1209':book.climbs['Full Stroke'],
         'path1201':book.climbs['Full Stroke'],
     })
Topo(name='The Good Warm Up',
     parent=book.formations['The Good Warm Up'],
     file_name='goodWarmUp.svg',
     size='h',
     routes={
         'path579':book.climbs['The Good Warm Up'],
         'path581':book.climbs['The Good Warm Up'],
     })
Topo(name='Gumby Wall',
     parent=book.formations['Gumby Wall'],
     file_name='gumby.svg',
     size='f',
     routes={
         'path643':book.climbs['Bag of Tricks'],
         'path594':book.climbs['Bag of Tricks'],
         'path434':book.climbs['Bag of Tricks'],
         'path432':book.climbs['Gumby Arête'],
         'path430':book.climbs['Gumby Arête'],
         'path428':book.climbs['Gumby Slab'],
         'path426':book.climbs['Gumby Slab'],
         'path424':book.climbs['Gumby Crack'],
         'path370':book.climbs['Gumby Crack'],
     })
Topo(name='Hanging Prow Project',
     parent=book.formations['Hanging Prow'],
     file_name='prowProj.svg',
     size='h',
     border='rect1075',
     routes={
         'path1600':book.climbs['Hanging Prow Project'],
         'path1598':book.climbs['Hanging Prow Project'],
         'path859':book.climbs['Hanging Prow Project'],
     })
Topo(name='Small',
     parent=book.formations['Small'],
     file_name='small.svg',
     size='h',
     routes={
         'path1740':book.climbs['Smol'],
         'path1738':book.climbs['Smol'],
         'path1736':book.climbs['Smol'],
         'path1276':book.climbs['Tip Toe'],
         'path1121':book.climbs['Tip Toe'],
     })
Topo(name='Spider Bumps',
     parent=book.routes['Spider Bumps'],
     file_name='spiderBumps.svg',
     size='h',
     routes={
         'path1879':book.climbs['Spider Bumps'],
         'path1877':book.climbs['Spider Bumps'],
     })
Topo(name='Farley',
     parent=book.routes['Belushi'],
     file_name='farley.svg',
     size='f',
     routes={
         'path2245':book.climbs['Farley Prep'],
         'path2243':book.climbs['Farley Prep'],
         'path2241':book.climbs['Farley Prep'],
         'path2239':book.climbs['Le Lemét'],
         'path2237':book.climbs['Le Lemét'],
         'path2232':book.climbs['Lippity Split'],
         'path2228':book.climbs['Lippity Split'],
         'path2230':book.climbs['Belushi'],
         'path2226':book.climbs['Belushi'],
     })
Topo(name='Frat House',
     parent=book.formations['Frat House'],
     file_name='fratHouse.svg',
     size='h',
     border='rect1761',
     routes={
         'path1063':book.climbs['Frat Mouse'],
         'path1061':book.climbs['Frat Mouse'],
         'path1059':book.climbs['Frat House'],
         'path1057':book.climbs['Frat House'],
     })
Topo(name='Jonah\'s Dab Rig',
     parent=book.formations['Jonah\'s Dab Rig'],
     file_name='jonah.svg',
     size='h',
     routes={
         'path1028':book.climbs['Jonah\'s Dab Rig'],
         'path1030':book.climbs['Jonah\'s Dab Rig'],
         'path1032':book.climbs['Jonah\'s Dab Rig'],
         'path1034':book.climbs['Workshop 68'],
         'path1036':book.climbs['Workshop 68'],
     })
Topo(name='Territorial Pissings',
     parent=book.formations['Pissing Boulder'],
     file_name='pissings.svg',
     size='h',
     routes={
         'path1462':book.climbs['Territorial Pissings'],
         'path1460':book.climbs['Territorial Pissings'],
     })
Topo(name='Garden Cliff Right Side',
     parent=book.climbs['John Henry\'s Hammer'],
     file_name='cliffs_main.svg',
     size='f',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path868':book.climbs['Yggdrasil'],
         'path870':book.climbs['John Henry\'s Hammer'],
         'path866':book.climbs['Scorpion Revenge'],
         'path864':book.climbs['Snug as a Snail'],
         'path862':book.climbs['Scorpion Hitchhikers Toilet Bowl Odyssey'],
         'path860':book.climbs['Daring to Fly'],
         'path858':book.climbs['Community'],
         'path299':book.climbs['Yggdrasil'],
         'path301':book.climbs['John Henry\'s Hammer'],
         'path297':book.climbs['Scorpion Revenge'],
         'path944':book.climbs['Snug as a Snail'],
         'path295':book.climbs['Scorpion Hitchhikers Toilet Bowl Odyssey'],
         'path293':book.climbs['Daring to Fly'],
         'path291':book.climbs['Community'],
     })
Topo(name='Garden Cliff Skink Area',
     parent=book.climbs['Stasis Chamber'],
     file_name='skink.svg',
     size='f',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path383':book.climbs['Anaphylactic Shock'],
         'path381':book.climbs['Anaphylactic Shock'],
         'path379':book.climbs['Fight Club (Round Two)'],
         'path377':book.climbs['Fight Club (Round Two)'],
         'path375':book.climbs['Cutting Crack'],
         'path373':book.climbs['Cutting Crack'],
         'path371':book.climbs['Butterfly Effect'],
         'path369':book.climbs['Butterfly Effect'],
         'path367':book.climbs['Slithering Skink'],
         'path365':book.climbs['Slithering Skink'],
         'path363':book.climbs['Stasis Chamber'],
         'path361':book.climbs['Stasis Chamber'],
         'path359':book.climbs['Lazarus'],
         'path357':book.climbs['Lazarus'],
         'path355':book.climbs['Wildlings'],
         'path353':book.climbs['Wildlings'],
         'path297':book.climbs['Rain Shadow'],
         'path295':book.climbs['Rain Shadow'],
         'path293':book.climbs['Lenticular Cloud Project'],
         'path291':book.climbs['Lenticular Cloud Project'],
     })
Topo(name='Garden Cliff Castle Black Area',
     parent=book.formations['Garden Cliff Middle'],
     file_name='castle2.svg',
     size='pr',
     loc='b',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path625':book.climbs['Heirloom Left Project'],
         'path623':book.climbs['Heirloom Left Project'],
         'path573':book.climbs['Vandals in the Graveyard'],
         'path571':book.climbs['Vandals in the Graveyard'],
         'path569':book.climbs['Vandals in the Graveyard'],
         'path567':book.climbs['Honeycomb Traverse'],
         'path565':book.climbs['Honeycomb Traverse'],
         'path562':book.climbs['Honeycomb Traverse'],
         'path560':book.climbs['Criss Cross Applesauce'],
         'path558':book.climbs['Criss Cross Applesauce'],
         'path556':book.climbs['Criss Cross Applesauce'],
         'path554':book.climbs['Spin Glass'],
         'path552':book.climbs['Spin Glass'],
         'path550':book.climbs['Spin Glass'],
         'path548':book.climbs['My Empire of Dirt'],
         'path546':book.climbs['My Empire of Dirt'],
         'path544':book.climbs['My Empire of Dirt'],
         'path542':book.climbs['Seraphim Nachash'],
         'path540':book.climbs['Seraphim Nachash'],
         'path538':book.climbs['Seraphim Nachash'],
         'path535':book.climbs['Littlest Birds'],
         'path531':book.climbs['Littlest Birds'],
         'path529':book.climbs['Littlest Birds'],
         'path533':book.climbs['Castle Black'],
         'path527':book.climbs['Castle Black'],
         'path525':book.climbs['Castle Black'],
         'path523':book.climbs['Chimeras'],
         'path521':book.climbs['Chimeras'],
         'path519':book.climbs['Chimeras'],
         'path463':book.climbs['Heirloom'],
         'path461':book.climbs['Heirloom'],
         'path459':book.climbs['Heirloom'],
         'path457':book.climbs['Vine Project'],
         'path455':book.climbs['Vine Project'],
         'path293':book.climbs['Vine Project'],
     })
Topo(name='Garden Cliff Nest Area',
     parent=book.formations['Garden Cliff Left Side'],
     file_name='nest2.svg',
     size='f',
     loc='b',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path475':book.climbs['Hive'],
         'path473':book.climbs['Hive'],
         'path471':book.climbs['Hive'],
         'path499':book.climbs['A Garden Called Peace'],
         'path469':book.climbs['A Garden Called Peace'],
         'path467':book.climbs['A Garden Called Peace'],
         'path465':book.climbs['Nest'],
         'path463':book.climbs['Nest'],
         'path461':book.climbs['Nest'],
         'path459':book.climbs['My Secret Garden'],
         'path457':book.climbs['My Secret Garden'],
         'path455':book.climbs['My Secret Garden'],
         'path451':book.climbs['Fertile Crescent'],
         'path449':book.climbs['Fertile Crescent'],
         'path351':book.climbs['Fertile Crescent'],
         'path349':book.climbs['Ovulation Send-sation'],
         'path347':book.climbs['Ovulation Send-sation'],
         'path293':book.climbs['Ovulation Send-sation'],
         'path1205':book.climbs['Ovulation Send-sation Extension'],
         'path1314':book.climbs['Ovulation Send-sation Extension'],
     })
Topo(name='Fairy Tale Wall',
     parent=book.formations['Fairy Tale Wall'],
     file_name='fairytale2.svg',
     size='h',
     loc='a',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path359':book.climbs['Fee-Fi-Fo-Fum'],
         'path357':book.climbs['Fee-Fi-Fo-Fum'],
         'path355':book.climbs['Feather of the Finest Falcon'],
         'path353':book.climbs['Feather of the Finest Falcon'],
         'path351':book.climbs['Death of Koschei the Deathless'],
         'path347':book.climbs['Death of Koschei the Deathless'],
         'path349':book.climbs['Baba Yaga'],
         'path291':book.climbs['Baba Yaga'],
     })
Topo(name='Thunderdome',
     parent=book.formations['Johny Cash\'s Thunderdome'],
     file_name='thunderDome2.svg',
     size='f',
     loc='b',
     paths={
        'topo_o': r'./maps/topos//cliffs/',
        'topo_i': r'./maps/topos//cliffs/'},
     routes={
         'path363':book.climbs['Stop Once to Wipe the Sweat Away'],
         'path361':book.climbs['A Million Dollars of Good'],
         'path359':book.climbs['I Will Let You Down'],
         'path357':book.climbs['I Will Let You Down'],
         'path355':book.climbs['I Fell for You Like a Child'],
         'path353':book.climbs['I Fell for You Like a Child'],
         'path351':book.climbs['I Dropped a Man in Reno'],
         'path349':book.climbs['I Dropped a Man in Reno'],
         'path347':book.climbs['Where Do You Go When the Sun Goes Down'],
         'path345':book.climbs['Where Do You Go When the Sun Goes Down'],
     })
Topo(name='Story of O',
     parent=book.formations['The Story of O Boulder'],
     file_name='storyO.svg',
     size='f',
     loc='e',
     border='rect878',
     routes={
         'path820':book.climbs['wikiFeet'],
         'path818':book.climbs['wikiFeet'],
         'path824':book.climbs['Arnold Palmer'],
         'path822':book.climbs['Arnold Palmer'],
         'path762':book.climbs['Santa Cruz Ski Trip'],
         'path760':book.climbs['Santa Cruz Ski Trip'],
         'path758':book.climbs['The Story of O'],
         'path707':book.climbs['The Story of O'],
     })
Topo(name='Hoggin Dogs',
     parent=book.formations['Titanium Boulder'],
     file_name='hogginDogs.svg',
     size='f',
     border='rect1047',
     routes={
         'path1033':book.climbs['Bilbo Baggins'],
         'path1031':book.climbs['Bilbo Baggins'],
         'path1029':book.climbs['Loggin Bogs'],
         'path1027':book.climbs['Loggin Bogs'],
         'path1025':book.climbs['Häagen Dogs'],
         'path1023':book.climbs['Häagen Dogs'],
         'path1021':book.climbs['Häagen Dogs'],
     })
Topo(name='Titanium',
     parent=book.climbs['Titanium'],
     file_name='titanium.svg',
     size='h',
     border='rect1180',
     routes={
         'path1178':book.climbs['Titanium'],
         'path1176':book.climbs['Titanium'],
     })
Topo(name='Foxglove',
     parent=book.formations['Foxglove Boulder'],
     file_name='foxglove.svg',
     size='h',
     loc='e',
     border='rect1328',
     routes={
         'path1319':book.climbs['Foxglove'],
         'path1317':book.climbs['Foxglove'],
     })
Topo(name='Pumpkin',
     parent=book.formations['Pumpkin'],
     file_name='pSpice.svg',
     size='h',
     routes={
         'path887':book.climbs['Pumpkin Spice'],
         'path885':book.climbs['Pumpkin Spice'],
         'path883':book.climbs['Pumpkin Spice'],
     })
Topo(name='Baseball',
     parent=book.formations['Baseball'],
     file_name='baseball.svg',
     size='h',
     routes={
         'path349':book.climbs['Baseball'],
         'path293':book.climbs['Baseball'],
         'path351':book.climbs['Bunt'],
         'path295':book.climbs['Bunt'],
     })
Topo(name='Bread Loaf',
     parent=book.routes['Worf'],
     file_name='breadLoaf.svg',
     size='f',
     border='rect1397',
     routes={
         'path2171':book.climbs['Bread Heel'],
         'path2169':book.climbs['Bread Heel'],
         'path543':book.climbs['Bread Loaf Left'],
         'path1100':book.climbs['Bread Loaf Left'],
         'path1104':book.climbs['Bread Loaf Traverse'],
         'path1153':book.climbs['Bread Loaf Traverse'],
         'path390':book.climbs['Breadwinner'],
         'path444':book.climbs['Breadwinner'],
         'path1155':book.climbs['Baker\'s Dozen'],
         'path1157':book.climbs['Baker\'s Dozen'],
     })
Topo(name='Bread Loaf2',
     parent=book.routes['Worf'],
     file_name='breadLoaf2.svg',
     size='h',
     loc='e',
     routes={
         'path1350':book.climbs['Worf'],
         'path1346':book.climbs['Worf'],
     })
Topo(name='Scratch and Spliff',
     parent=book.routes['Spliff'],
     file_name='scratchSpliff.svg',
     size='h',
     routes={
         'path1921':book.climbs['Spliff'],
         'path1919':book.climbs['Spliff'],
         'path1925':book.climbs['Scratch and Spliff Traverse'],
         'path1923':book.climbs['Scratch and Spliff Traverse'],
         'path1917':book.climbs['Roach'],
         'path1915':book.climbs['Roach'],
         'path2515':book.climbs['For What it\'s Worth'],
         'path2513':book.climbs['For What it\'s Worth'],
     })
Topo(name='Scratch and Spliff 2',
     parent=book.formations['Scratch and Spliff'],
     file_name='scratchSpliff2.svg',
     size='f',
     routes={
         'path2067':book.climbs['Scratch and Spliff Traverse'],
         'path2065':book.climbs['Scratch and Spliff Traverse'],
         'path2080':book.climbs['Spliff'],
         'path2075':book.climbs['Spliff'],
         'path2077':book.climbs['Scratch'],
         'path2073':book.climbs['Scratch'],
         'path2071':book.climbs['Late Start'],
         'path2069':book.climbs['Late Start'],
     })
Topo(name='Scratch and Spliff 3',
     parent=book.routes['Caliban\'s War'],
     file_name='scratchSpliff3.svg',
     size='h',
     routes={
         'path2226':book.climbs['Caliban\'s War'],
         'path2224':book.climbs['Caliban\'s War'],
         'path2222':book.climbs['Caliban\'s War'],
         'path2228':book.climbs['Stoned Age'],
         'path2230':book.climbs['Stoned Age'],
     })
Topo(name='Kick It',
     parent=book.formations['Kick It'],
     file_name='kickIt.svg',
     size='h',
     border='rect653',
     routes={
         'path599':book.climbs['Kick It'],
         'path595':book.climbs['Kick It'],
         'path597':book.climbs['Kick It'],
     })
Topo(name='Algebra',
     parent=book.formations['Algebra'],
     file_name='algebra.svg',
     size='h',
     border='rect650',
     routes={
         'path648':book.climbs['Algebra'],
         'path646':book.climbs['Algebra'],
         'path644':book.climbs['Algebra'],
     })
Topo(name='MGB',
     parent=book.formations['Mega Good Boulder'],
     file_name='MGB.svg',
     size='h',
     border='rect401',
     routes={
         'path347':book.climbs['MGB'],
         'path293':book.climbs['MGB'],
     })
Topo(name='Dr. Strangelove',
     parent=book.formations['Dr. Strangelove'],
     file_name='strangeLove.svg',
     size='h',
     border='rect808',
     routes={
         'path797':book.climbs['War Room'],
         'path795':book.climbs['War Room'],
         'path793':book.climbs['Dr. Strangelove'],
         'path791':book.climbs['Dr. Strangelove'],
     })
Topo(name='Crack',
     parent=book.formations['Crack Boulder'],
     file_name='crack.svg',
     size='h',
     border='rect505',
     routes={
         'path451':book.climbs['Crack 2'],
         'path449':book.climbs['Crack 2'],
         'path445':book.climbs['Jugs'],
         'path391':book.climbs['Jugs'],
     })
Topo(name='Machete Monkey',
     parent=book.formations['Machete Monkey'],
     file_name='machete.svg',
     size='h',
     border='rect796',
     routes={
         'path588':book.climbs['Machete Monkey Left'],
         'path586':book.climbs['Machete Monkey Left'],
         'path794':book.climbs['Machete Man'],
         'path790':book.climbs['Machete Man'],
         'path792':book.climbs['Machete Monkey'],
         'path788':book.climbs['Machete Monkey'],
     })
Topo(name='June 24th',
     parent=book.formations['June 24th'],
     file_name='June24.svg',
     size='h',
     border='rect943',
     routes={
         'path941':book.climbs['June 24th'],
         'path939':book.climbs['June 24th'],
         'path937':book.climbs['June 1'],
         'path935':book.climbs['June 1'],
         'path1016':book.climbs['June 69th High Start'],
         'path1018':book.climbs['June 69th High Start'],
         'path1020':book.climbs['June 69th'],
         'path1022':book.climbs['June 69th'],
     })
Topo(name='Young Ju¢y',
     parent=book.formations['Young Ju¢y'],
     file_name='young.svg',
     size='f',
     loc='e',
     routes={
         'path572':book.climbs['Loosey Ju¢y'],
         'path570':book.climbs['Loosey Ju¢y'],
         'path568':book.climbs['Juice WRLD'],
         'path418':book.climbs['Juice WRLD'],
         'path1086':book.climbs['Young Ju¢y'],
         'path1084':book.climbs['Young Ju¢y'],
         'path1082':book.climbs['Young Ju¢y'],
     })
Topo(name='Duck Twirler',
     parent=book.formations['Duck Twirler'],
     file_name='duckTwirl.svg',
     size='f',
     loc='e',
     routes={
         'path758':book.climbs['Screaming at a Wall'],
         'path704':book.climbs['Screaming at a Wall'],
         'path702':book.climbs['Screaming at a Wall'],
         'path1223':book.climbs['Anti-Tiff'],
         'path1225':book.climbs['Anti-Tiff'],
         'path1227':book.climbs['Duck Twirler'],
         'path1229':book.climbs['Duck Twirler'],
         'path1231':book.climbs['Duck Twirler'],
         'path1233':book.climbs['Deforestation'],
         'path1235':book.climbs['Deforestation'],
         'path1237':book.climbs['Deforestation'],
     })
Topo(name='Duck Twirler 2',
     parent=book.formations['Duck Twirler'],
     file_name='duckTwirl2.svg',
     size='h',
     routes={
         'path1379':book.climbs['DT 1'],
         'path1381':book.climbs['DT 1'],
         'path1383':book.climbs['DT 1'],
         'path1385':book.climbs['Anti-Tiff'],
         'path1387':book.climbs['Anti-Tiff'],
     })
Topo(name='Deep Sea Diver',
     parent=book.formations['Deep Sea Diver'],
     file_name='deepSea.svg',
     size='f',
     loc='e',
     border='rect513',
     routes={
         'path459':book.climbs['DSD 4'],
         'path457':book.climbs['DSD 4'],
         'path453':book.climbs['DSD 3'],
         'path451':book.climbs['DSD 3'],
         'path449':book.climbs['Ya Ya Crack'],
         'path447':book.climbs['Ya Ya Crack'],
         'path443':book.climbs['Deep Sea Diver'],
         'path293':book.climbs['Deep Sea Diver'],
     })
Topo(name='Jaws',
     parent=book.formations['Jaws'],
     file_name='Jaws.svg',
     size='h',
     loc='b',
     border='rect559',
     routes={
         'path451':book.climbs['Remora'],
         'path449':book.climbs['Remora'],
         'path351':book.climbs['Remora'],
         'path349':book.climbs['Jaws'],
         'path295':book.climbs['Jaws'],
         'path293':book.climbs['Jaws'],
     })
Topo(name='Prince Albert',
     parent=book.formations['Prince Albert'],
     file_name='princeAlbert.svg',
     size='h',
     loc='e',
     border='rect1003',
     routes={
         'path449':book.climbs['PA 2'],
         'path447':book.climbs['PA 2'],
         'path445':book.climbs['Prince Albert'],
         'path391':book.climbs['Prince Albert'],
         'path293':book.climbs['Prince Albert'],
     })
Topo(name='Star Gazer',
     parent=book.formations['Star Gazer'],
     file_name='StarGazer.svg',
     size='h',
     loc='b',
     border='rect463',
     routes={
         'path293':book.climbs['Galileo'],
         'path347':book.climbs['Galileo'],
         'path349':book.climbs['Fleming'],
         'path351':book.climbs['Fleming'],
         'path353':book.climbs['Huygens'],
         'path355':book.climbs['Huygens'],
     })
Topo(name='Dig Dug',
     parent=book.formations['Dig Dug'],
     file_name='DigDug.svg',
     size='f',
     loc='b',
     border='rect728',
     routes={
         'path726':book.climbs['Tear Duct Finish'],
         'path724':book.climbs['Tear Duct Finish'],
         'path722':book.climbs['Tear Duct Direct'],
         'path718':book.climbs['Tear Duct Direct'],
         'path720':book.climbs['Tear Duct'],
         'path716':book.climbs['Tear Duct'],
         'path714':book.climbs['Fly Guy SDS'],
         'path712':book.climbs['Fly Guy SDS'],
         'path710':book.climbs['Fly Guy'],
         'path708':book.climbs['Fly Guy'],
         'path706':book.climbs['Mud Flaps'],
         'path608':book.climbs['Mud Flaps'],
         'path606':book.climbs['Skrunch'],
         'path604':book.climbs['Skrunch'],
     })
Topo(name='Grizzly Face',
     parent=book.formations['Grizzly Face'],
     file_name='GrizzlyFace.svg',
     size='h',
     loc='b',
     border='rect889',
     routes={
         'path887':book.climbs['Baloo'],
         'path885':book.climbs['Baloo'],
         'path883':book.climbs['Br\'er Bear'],
         'path877':book.climbs['Br\'er Bear'],
     })
Topo(name='Bear Back',
     parent=book.formations['Bear Back'],
     file_name='BearBack.svg',
     size='f',
     loc='b',
     border='rect1044',
     routes={
         'path1042':book.climbs['Chet Ripley'],
         'path1040':book.climbs['Chet Ripley'],
         'path1038':book.climbs['Roman Craig'],
         'path1036':book.climbs['Roman Craig'],
         'path1034':book.climbs['Wally'],
         'path1032':book.climbs['Wally'],
         'path1030':book.climbs['Bald Bear'],
         'path1028':book.climbs['Bald Bear'],
     })
Topo(name='Double Stump',
     parent=book.formations['Double Stump'],
     file_name='DoubleStump.svg',
     size='h',
     loc='b',
     border='rect1199',
     routes={
         'path1197':book.climbs['Double Stump Project Right'],
         'path1195':book.climbs['Double Stump Project Right'],
         'path1193':book.climbs['Double Stump Project'],
         'path1191':book.climbs['Double Stump Project'],
         'path1189':book.climbs['Ballistics Dummy'],
         'path1187':book.climbs['Ballistics Dummy'],
     })
Topo(name='Double Stump 2',
     parent=book.climbs['Chump Mantle'],
     file_name='DoubleStump2.svg',
     size='h',
     loc='b',
     border='rect1344',
     routes={
         'path1342':book.climbs['Chump Mantle'],
         'path1340':book.climbs['Chump Mantle'],
     })
Topo(name='Cuneiform',
     parent=book.formations['Cuneiform'],
     file_name='Cuneiform.svg',
     size='f',
     loc='b',
     border='rect1497',
     routes={
         'path1495':book.climbs['Eridu'],
         'path1493':book.climbs['Eridu'],
         'path1491':book.climbs['Cuneiform Project'],
         'path1489':book.climbs['Cuneiform Project'],
         'path1487':book.climbs['Walk the Line'],
         'path1485':book.climbs['Walk the Line'],
         'path1483':book.climbs['Cuneiform1'],
         'path1481':book.climbs['Cuneiform1'],
     })
Topo(name='Monorail',
     parent=book.formations['Monorail'],
     file_name='Monorail.svg',
     size='f',
     routes={
         'path973':book.climbs['Deliverance'],
         'path975':book.climbs['Deliverance'],
         'path446':book.climbs['Deliverance'],
         'path448':book.climbs['Deliverance Low'],
         'path502':book.climbs['Deliverance Low'],
         'path971':book.climbs['Monorail Extension Project'],
         'path969':book.climbs['Monorail Extension Project'],
         'path967':book.climbs['Monorail'],
         'path763':book.climbs['Monorail'],
     })
Topo(name='Yo Mamma',
     parent=book.formations['Yo Mamma Boulder'],
     file_name='YoMamma.svg',
     size='h',
     border='rect966',
     routes={
         'path955':book.climbs['Ugly Face'],
         'path953':book.climbs['Ugly Face'],
         'path951':book.climbs['Binding of Isaac'],
         'path947':book.climbs['Binding of Isaac'],
     })
Topo(name='4.5',
     parent=book.formations['The 4.5'],
     file_name='45.svg',
     size='f',
     border='rect1383',
     routes={
         'path1329':book.climbs['Falcon\'s Reach'],
         'path1323':book.climbs['Falcon\'s Reach'],
         'path1327':book.climbs['Teenage Libertarians'],
         'path1321':book.climbs['Teenage Libertarians'],
         'path1325':book.climbs['Chicken Tendies'],
         'path764': book.climbs['Chicken Tendies'],
     })
Topo(name='Dab Rig',
     parent=book.formations['The Dab Rig'],
     file_name='DabRig.svg',
     size='f',
     routes={
         'path456':book.climbs['Dank Commander'],
         'path454':book.climbs['Dank Commander'],
         'path452':book.climbs['Unsalted Almonds'],
         'path398':book.climbs['Unsalted Almonds'],
         'path300':book.climbs['Unsalted Almonds'],
     })
Topo(name='Big Iron',
     parent=book.formations['Big Iron'],
     file_name='bigIron.svg',
     size='h',
     loc='b',
     border='rect522',
     routes={
         'path456': book.climbs['No Stone Unturned'],
         'path454': book.climbs['No Stone Unturned'],
         'path452': book.climbs['Big Iron Direct'],
         'path450': book.climbs['Big Iron Direct'],
         'path445': book.climbs['Big Iron'],
         'path447': book.climbs['Big Iron'],
         'path293': book.climbs['Big Iron'],
     })
Topo(name='Wild Roses',
     parent=book.climbs['Wild Roses'],
     file_name='wildRoses.svg',
     size='h',
     routes={
         'path666': book.climbs['Wild Roses'],
         'path664': book.climbs['Wild Roses'],
     })
AreaMap(name='The Garden Main Area Overview',
        parent=book.areas['The Garden Main'],
        file_name='Garden.svg',
        sub_areas={
            'rect2027': book.subareas['Big'],
            'rect1376': book.subareas['Azain'],
            'rect2313': book.subareas['Entrance Area'],
            'rect2908': book.subareas['François'],
            'rect3027': book.subareas['Fight Club'],
            'rect3200': book.subareas['Meth Lab'],
            'rect3386': book.subareas['Undertow'],
            'rect380': book.subareas['Child of God'],
        },
        layers=['Base'],
        size='pr',
        loc='b')
AreaMap(name='The Garden Cliff Overview',
        parent=book.areas['Garden Cliffs'],
        file_name='Cliffs.svg',
        sub_areas={
            'rect5139': book.subareas['Fairy Tale Wall'],
            'rect5141': book.subareas['Cabbage Patch/ Thunderdome'],
            'rect5032': book.subareas['The Garden Cliff'],
        },
        layers=['base'],
        border='rect5165',
        size='h',)
AreaMap(name='Armageddon Area Overview',
        parent=book.areas['Upper Garden'],
        file_name='upperGarden.svg',
        sub_areas={
            'rect3951': book.subareas['Upper Forest'],
            'rect27128': book.subareas['The Bread Loaves'],
            'rect27051': book.subareas['entranceUpper'],
            'rect14556': book.subareas['Dr. Strangelove'],
            'rect14669': book.subareas['Machete Monkey'],
            'rect2363': book.subareas['Middle Garden'],
        },
        layers=['Base_Upper', 'border'],
        border='rect27048',
        size='f',
        loc='b')
SubAreaMap(name='Entrance Area map',
           parent=book.subareas['Entrance Area'],
           out_file_name='entrance_c.png',
           file_name='Garden.svg',
           layers=['Entrance', 'Base'],
           border='rect2313',
           routes={
           'path1767':book.climbs['Toilet Bowl Traverse'],
           'path1769':book.climbs['Toilet Bowl'],
           'path1771':book.climbs['Donatello'],
           'path1773':book.climbs['Leonardo'],
           'path1775':book.climbs['Raphael Crack'],
           'path1777':book.climbs['Overhand'],
           'path841':book.climbs['Goose Egg'],
           'path1779':book.climbs['Three Star Ledge'],
           'path1781':book.climbs['All Sorts of Ease'],
           'path1783':book.climbs['In the Shadow of Giants'],
           'path1785':book.climbs['Tonsil'],
           'path1787':book.climbs['Boys in the Woods'],
           'path1789':book.climbs['Ice Cubes Shiny Jerry Curl'],
           'path1791':book.climbs['Tree Slab'],
           'path2200':book.climbs['Spider Bumps'],
           })
SubAreaMap(name='Fight Club Area map',
           parent=book.subareas['Fight Club'],
           out_file_name='fightClub_c.png',
           file_name='Garden.svg',
           layers=['Fight Club', 'Base'],
           border='rect3027',
           size='f',
           routes={
           'path876':book.climbs['Unknown on E\'s Dirty B'],
           'path874':book.climbs['Green Hell'],
           'path4077':book.climbs['E\'s Dirty B'],
           'path1519':book.climbs['Jim Halpert'],
           'path878':book.climbs['Michael Scott'],
           'path1517':book.climbs['Daryl Philbin'],
           'path1515':book.climbs['Vince'],
           'path1513':book.climbs['The Ear'],
           'path1511':book.climbs['Fight Club 2'],
           'path1509':book.climbs['Project Mayhem'],
           'path1507':book.climbs['Trust'],
           'path1505':book.climbs['Austin Powers'],
           'path1503':book.climbs['Dr. Evil'],
           'path1174':book.climbs['Dwight Schrute'],
           'path1086':book.climbs['Backside of Office'],
           })
SubAreaMap(name='Undertow area map',
           parent=book.subareas['Undertow'],
           out_file_name='undertow_c.png',
           file_name='Garden.svg',
           layers=['Undertow', 'Base'],
           border='rect3386',
           routes={
               'path1244':book.climbs['Silly Steep Mantle'],
               'path1246':book.climbs['Undertow'],
               'path1248':book.climbs['Tidepool'],
               'path1250':book.climbs['Chock Stone Highball'],
               'path1252':book.climbs['Car Alarm Traverse'],
               'path1254':book.climbs['2 Ton Chevy'],
               'path1256':book.climbs['Pup Truck'],
               'path1258':book.climbs['Comp Route'],
               'path1260':book.climbs['Panic Button'],
               'path3384':book.climbs['Bubonic Plague'],
               'path872':book.climbs['Hanging Prow Project'],
           })
SubAreaMap(name='Meth Lab area map',
           parent=book.subareas['Meth Lab'],
           out_file_name='methLab_c.png',
           file_name='Garden.svg',
           layers=['Meth Lab', 'Base'],
           border='rect3200',
           routes={
               'path992':book.climbs['Turd Party UR Invited'],
               'path1196':book.climbs['Phallacy'],
               'path771':book.climbs['West Arête'],
               'path521':book.climbs['Southern Discomfort'],
               'path760':book.climbs['Don\'t Blow the Jug'],
               'path762':book.climbs['Trust Issues'],
               'path764':book.climbs['Leave it to Jesus'],
               'path766':book.climbs['Smackdown'],
               'path768':book.climbs['Heisenburg'],
               'path770':book.climbs['Guillotine'],
               'path772':book.climbs['Octernal'],
               'path774':book.climbs['Two Blows One Stroke'],
               'path776':book.climbs['E\'s'],
               'path778':book.climbs['Enchilada'],
               'path1218':book.climbs['Little Enchilada'],
               'path780':book.climbs['Swollen Member'],
               'path782':book.climbs['Meth Lab Highball'],
               'path784':book.climbs['The Bubbler'],
               'path4341':book.climbs['Meth Lab Project'],
               'path426':book.climbs['Slam Dunk'],
               'path428':book.climbs['Gargoyle'],
               'path1731':book.climbs['Chillum'],
           })
SubAreaMap(name='Big area map',
           parent=book.subareas['Big'],
           out_file_name='big_c.png',
           file_name='Garden.svg',
           routes={
               'path5664':book.climbs['Frontside Baldo'],
               'path583':book.climbs['Slabarific'],
               'path1027':book.climbs['Big Slab Right'],
               'path5662':book.climbs['Hueco Wabo'],
               'path5660':book.climbs['All Berned Up'],
               'path410':book.climbs['Mini Hydrotube'],
               'path528':book.climbs['Pockets'],
               'path5658':book.climbs['Bitchin Corners'],
               'path5658-4':book.climbs['Smol'],
               'path880':book.climbs['Cargo Net Project'],
               'path1395':book.climbs['Classique'],
               'path1397':book.climbs['Crazy Cool Arête'],
           },
           layers=['Big', 'Base'],
           border='rect2027'),
SubAreaMap(name='Azain area map',
           parent=book.subareas['Azain'],
           out_file_name='azain_c.png',
           file_name='Garden.svg',
           size='h',
           routes={
               'path994':book.climbs['From Minnesota with Love'],
               'path720':book.climbs['Ground up Blowie'],
               'path718':book.climbs['Nightcrawler'],
               'path716':book.climbs['The Good Slab'],
               'path714':book.climbs['The Good'],
               'path712':book.climbs['Another'],
               'path710':book.climbs['Snakes and Martyrs'],
               'path708':book.climbs['Next to the Good'],
               'path740':book.climbs['Into the Light'],
               'path742':book.climbs['Garden Groove'],
               'path1962':book.climbs['Simpson\'s First'],
           },
           layers=['Azain', 'Base'],
           border='rect1376')
SubAreaMap(name='Child of God area map',
           parent=book.subareas['Child of God'],
           out_file_name='child_o_god_c.png',
           file_name='Garden.svg',
           size='f',
           routes={
               'ellipse374':book.climbs['Gumby Crack'],
               'circle372':book.climbs['Gumby Slab'],
               'circle370':book.climbs['Gumby Arête'],
               'ellipse368':book.climbs['The Siren'],
               'ellipse366':book.climbs['Garden Variety'],
               'ellipse364':book.climbs['The Arboretum'],
               'ellipse362':book.climbs['Full Stroke'],
               'ellipse360':book.climbs['Philanthropy'],
               'circle358':book.climbs['Locksmith'],
               'path1391':book.climbs['Oregon Arête'],
           },
           layers=['Child of God', 'Base'],
           border='rect380')
SubAreaMap(name='François area map',
           parent=book.subareas['François'],
           out_file_name='Big Frank_c.png',
           file_name='Garden.svg',
           layers=['Big Fred', 'Base'],
           border='rect2908',
           routes={
               'path1194':book.climbs['Fern Sully'],
               'path714-5':book.climbs['Scary Grandma'],
               'path712-7':book.climbs['Angry Mom'],
               'path712-6':book.climbs['Easy Grandma'],
               'path710-5':book.climbs['François'],
               'path1964':book.climbs['Geodesic Wiener'],
               'path1966':book.climbs['Shake it Out Frank'],
               'path1571':book.climbs['Schrödinger Project'],
           })
SubAreaMap(name='Pink Tag area map',
           parent=book.areas['Pink Tag Boulders'],
           out_file_name='Pink Tag_c.png',
           file_name='Garden.svg',
           size='f',
           layers=['Pink Tag', 'Base'],
           border='rect3553',
           routes={
               'path3723':book.climbs['Farley Prep'],
               'path3721':book.climbs['Le Lemét'],
               'path3719':book.climbs['Belushi'],
               'path3717':book.climbs['Frat House'],
               'path3715':book.climbs['Workshop 68'],
               'path3713':book.climbs['Territorial Pissings'],
           })
SubAreaMap(name='Upper Forest map',
           parent=book.subareas['Upper Forest'],
           out_file_name='upperForest_c.png',
           file_name='upperGarden.svg',
           layers=['Upper Forest', 'Base_Upper'],
           border='rect3951',
           size='f',
           routes={
               'path13860':book.climbs['Foxglove'],
               'path13858':book.climbs['Titanium'],
               'path13856':book.climbs['Häagen Dogs'],
               'path13854':book.climbs['Loggin Bogs'],
               'path13852':book.climbs['wikiFeet'],
               'path13850':book.climbs['Santa Cruz Ski Trip'],
               'path13848':book.climbs['The Story of O'],
           })
SubAreaMap(name='Entrance area map',
           parent=book.subareas['entranceUpper'],
           out_file_name='entranceUpper_c.png',
           file_name='upperGarden.svg',
           layers=['Entrance', 'Base_Upper'],
           border='rect27051',
           routes={
               'path27105':book.climbs['Pumpkin Spice'],
               'path27107':book.climbs['Baseball'],
               'path27109':book.climbs['Bunt'],
           })
SubAreaMap(name='Bread loaf/Scratch and Spliff area map',
           parent=book.subareas['The Bread Loaves'],
           out_file_name='bread_c.png',
           file_name='upperGarden.svg',
           layers=['Bread', 'Base_Upper'],
           border='rect27128',
           size='f',
           routes={
               'path27126':book.climbs['Caliban\'s War'],
               'path27124':book.climbs['Scratch'],
               'path27122':book.climbs['Spliff'],
               'path27120':book.climbs['Scratch and Spliff Traverse'],
               'path27118':book.climbs['For What it\'s Worth'],
               'path27116':book.climbs['Worf'],
               'path27114':book.climbs['Bread Loaf Traverse'],
               'path27112':book.climbs['Bread Loaf Left'],
           })
SubAreaMap(name='Strangelove',
           parent=book.subareas['Dr. Strangelove'],
           out_file_name='strangelove_c.png',
           file_name='upperGarden.svg',
           layers=['Strangelove', 'Base_Upper'],
           border='rect14556',
           routes={
               'path14666':book.climbs['Kick It'],
               'path2130':book.climbs['Algebra'],
               'path14664':book.climbs['War Room'],
               'path14662':book.climbs['Dr. Strangelove'],
               'path756':book.climbs['MGB'],
           })
SubAreaMap(name='Machete Monkey',
           parent=book.subareas['Machete Monkey'],
           out_file_name='Machete.png',
           file_name='upperGarden.svg',
           layers=['Machete Monkey', 'Base_Upper'],
           border='rect14669',
           routes={
               'path1393':book.climbs['June 69th'],
               'path2024':book.climbs['Deforestation'],
               'path2022':book.climbs['Duck Twirler'],
               'path1121':book.climbs['Screaming at a Wall'],
               'path2020':book.climbs['Anti-Tiff'],
               'path2018':book.climbs['DT 1'],
               'path2016':book.climbs['Crack 2'],
               'path2014':book.climbs['Jugs'],
               'path1908':book.climbs['June 1'],
               'path23841':book.climbs['June 24th'],
               'path14673':book.climbs['Young Ju¢y'],
               'path2023':book.climbs['Machete 3'],
               'path14671':book.climbs['Machete Monkey'],
               'path1009':book.climbs['Loosey Ju¢y'],
           })
SubAreaMap(name='Middle Garden',
           parent=book.subareas['Middle Garden'],
           out_file_name='MiddleGarden.png',
           file_name='upperGarden.svg',
           layers=['Middle', 'Base_Upper'],
           border='rect2363',
           routes={
               'path1678':book.climbs['Jaws'],
               'path672':book.climbs['DSD 4'],
               'path670':book.climbs['DSD 3'],
               'path668':book.climbs['Ya Ya Crack'],
               'path666':book.climbs['Deep Sea Diver'],
               'path664':book.climbs['Easy Up, Easy Down'],
               'path662':book.climbs['PA 2'],
               'path660':book.climbs['Prince Albert'],
           })
SubAreaMap(name='Redneck Riviera area map',
           parent=book.subareas['Redneck Riviera'],
           file_name='redneck.svg',
           layers=['Redneck', 'Base'],
           border='rect3479',
           size='h',
           routes={
               'path3423':book.climbs['Pony Boy'],
               'path3421':book.climbs['Monorail'],
               'path3419':book.climbs['Ugly Face'],
               'path3417':book.climbs['Binding of Isaac'],
               'path3415':book.climbs['Moss Boss'],
               'path3413':book.climbs['Chicken Tendies'],
               'path3411':book.climbs['Teenage Libertarians'],
               'path3357':book.climbs['Falcon\'s Reach'],
           })
           
           
if __name__ == '__main__':
    sys.exit()