from dataStructure.Photo import Photo
from dataStructure.Topo import Topo
from dataStructure.AreaMap import AreaMap
from dataStructure.SubAreaMap import SubAreaMap
from data.GB_Book import book

Topo(name='Garden Cliff Right Side',
     parent=book.climbs['John Henry\'s Hammer'],
     file_name='cliffs_main.svg',
     size='f',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path868':book.climbs['Yggdrasil'],
         'path870':book.climbs['John Henry\'s Hammer'],
         'path866':book.climbs['Scorpion Revenge'],
         'path864':book.climbs['Snug as a Snail'],
         'path862':book.climbs['Scorpion Hitchhikers Toilet Bowl Odyssey'],
         'path860':book.climbs['Daring to Fly'],
         'path858':book.climbs['Community'],
         'path299':book.climbs['Yggdrasil'],
         'path301':book.climbs['John Henry\'s Hammer'],
         'path297':book.climbs['Scorpion Revenge'],
         'path944':book.climbs['Snug as a Snail'],
         'path295':book.climbs['Scorpion Hitchhikers Toilet Bowl Odyssey'],
         'path293':book.climbs['Daring to Fly'],
         'path291':book.climbs['Community'],
     })
Topo(name='Garden Cliff Skink Area',
     parent=book.climbs['Stasis Chamber'],
     file_name='skink.svg',
     size='f',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path383':book.climbs['Anaphylactic Shock'],
         'path381':book.climbs['Anaphylactic Shock'],
         'path379':book.climbs['Fight Club (Round Two)'],
         'path377':book.climbs['Fight Club (Round Two)'],
         'path375':book.climbs['Cutting Crack'],
         'path373':book.climbs['Cutting Crack'],
         'path371':book.climbs['Butterfly Effect'],
         'path369':book.climbs['Butterfly Effect'],
         'path367':book.climbs['Slithering Skink'],
         'path365':book.climbs['Slithering Skink'],
         'path363':book.climbs['Stasis Chamber'],
         'path361':book.climbs['Stasis Chamber'],
         'path359':book.climbs['Lazarus'],
         'path357':book.climbs['Lazarus'],
         'path355':book.climbs['Wildlings'],
         'path353':book.climbs['Wildlings'],
         'path297':book.climbs['Rain Shadow'],
         'path295':book.climbs['Rain Shadow'],
         'path293':book.climbs['Lenticular Cloud'],
         'path291':book.climbs['Lenticular Cloud'],
     })
Topo(name='Garden Cliff Castle Black Area',
     parent=book.formations['Garden Cliff Middle'],
     file_name='castle2.svg',
     size='pr',
     loc='b',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path625':book.climbs['Heirloom Left Project'],
         'path623':book.climbs['Heirloom Left Project'],
         'path573':book.climbs['Vandals in the Graveyard'],
         'path571':book.climbs['Vandals in the Graveyard'],
         'path569':book.climbs['Vandals in the Graveyard'],
         'path567':book.climbs['Honeycomb Traverse'],
         'path565':book.climbs['Honeycomb Traverse'],
         'path562':book.climbs['Honeycomb Traverse'],
         'path560':book.climbs['Criss Cross Applesauce'],
         'path558':book.climbs['Criss Cross Applesauce'],
         'path556':book.climbs['Criss Cross Applesauce'],
         'path554':book.climbs['Spin Glass'],
         'path552':book.climbs['Spin Glass'],
         'path550':book.climbs['Spin Glass'],
         'path548':book.climbs['My Empire of Dirt'],
         'path546':book.climbs['My Empire of Dirt'],
         'path544':book.climbs['My Empire of Dirt'],
         'path542':book.climbs['Seraphim Nachash'],
         'path540':book.climbs['Seraphim Nachash'],
         'path538':book.climbs['Seraphim Nachash'],
         'path535':book.climbs['Littlest Birds'],
         'path531':book.climbs['Littlest Birds'],
         'path529':book.climbs['Littlest Birds'],
         'path533':book.climbs['Castle Black'],
         'path527':book.climbs['Castle Black'],
         'path525':book.climbs['Castle Black'],
         'path523':book.climbs['Chimeras'],
         'path521':book.climbs['Chimeras'],
         'path519':book.climbs['Chimeras'],
         'path463':book.climbs['Heirloom'],
         'path461':book.climbs['Heirloom'],
         'path459':book.climbs['Heirloom'],
         'path457':book.climbs['Vine Project'],
         'path455':book.climbs['Vine Project'],
         'path293':book.climbs['Vine Project'],
     })
Topo(name='Garden Cliff Nest Area',
     parent=book.formations['Garden Cliff Left Side'],
     file_name='nest2.svg',
     size='f',
     loc='b',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path475':book.climbs['Hive'],
         'path473':book.climbs['Hive'],
         'path471':book.climbs['Hive'],
         'path499':book.climbs['A Garden Called Peace'],
         'path469':book.climbs['A Garden Called Peace'],
         'path467':book.climbs['A Garden Called Peace'],
         'path465':book.climbs['Nest'],
         'path463':book.climbs['Nest'],
         'path461':book.climbs['Nest'],
         'path459':book.climbs['My Secret Garden'],
         'path457':book.climbs['My Secret Garden'],
         'path455':book.climbs['My Secret Garden'],
         'path451':book.climbs['Fertile Crescent'],
         'path449':book.climbs['Fertile Crescent'],
         'path351':book.climbs['Fertile Crescent'],
         'path349':book.climbs['Ovulation Send-sation'],
         'path347':book.climbs['Ovulation Send-sation'],
         'path293':book.climbs['Ovulation Send-sation'],
         'path1205':book.climbs['Ovulation Send-sation Extension'],
         'path1314':book.climbs['Ovulation Send-sation Extension'],
     })
Topo(name='Fairy Tale Wall',
     parent=book.subareas['Fairy Tale Wall'],
     file_name='fairytale2.svg',
     size='f',
     width='0.75',
     loc='b',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path359':book.climbs['Fee-Fi-Fo-Fum'],
         'path357':book.climbs['Fee-Fi-Fo-Fum'],
         'path355':book.climbs['Feather of the Finest Falcon'],
         'path353':book.climbs['Feather of the Finest Falcon'],
         'path351':book.climbs['Death of Koschei the Deathless'],
         'path347':book.climbs['Death of Koschei the Deathless'],
         'path349':book.climbs['Baba Yaga'],
         'path291':book.climbs['Baba Yaga'],
     })
Topo(name='Thunderdome',
     parent=book.formations['Thunderdome'],
     file_name='thunderDome2.svg',
     size='f',
     loc='b',
     paths={
        'topo_o': r'./images/maps/topos/Cliffs/',
        'topo_i': r'./images/maps/topos/Cliffs/'},
     routes={
         'path363':book.climbs['Stop Once to Wipe the Sweat Away'],
         'path361':book.climbs['A Million Dollars of Good'],
         'path359':book.climbs['I Will Let You Down'],
         'path357':book.climbs['I Will Let You Down'],
         'path355':book.climbs['I Fell for You Like a Child'],
         'path353':book.climbs['I Fell for You Like a Child'],
         'path351':book.climbs['I Dropped a Man in Reno'],
         'path349':book.climbs['I Dropped a Man in Reno'],
         'path347':book.climbs['Where Do You Go When the Sun Goes Down'],
         'path345':book.climbs['Where Do You Go When the Sun Goes Down'],
     })
     
if __name__ == '__main__':
    sys.exit()
